/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/pricingengines/credit/integralcdsengine.hpp>
#include <ql/pricingengines/credit/midpointcdsengine.hpp>

