/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */


#include <ql/models/marketmodels/all.hpp>
#include <ql/models/shortrate/all.hpp>
#include <ql/models/volatility/all.hpp>
