.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH AMERICANOPTION 1 "27 July 2003" QuantLib
.SH NAME
AmericanOption - Example of using QuantLib
.SH SYNOPSIS
.B AmericanOption
.SH DESCRIPTION
.PP
.B AmericanOption
is an example of using \fIQuantLib\fP.

It computes the value of an American Call option using several different methods.
.SH SEE ALSO
The source code 
.IR AmericanOption.cpp ,
.BR EuropeanOption (1),
.BR DiscreteHedging (1),
.BR SwapValuation (1),
the QuantLib documentation and website at
.IR http://quantlib.org .

.SH AUTHORS
The QuantLib Group (see 
.IR Authors.txt ).

This manual page was added by Dirk Eddelbuettel <edd@debian.org>, 
the Debian GNU/Linux maintainer for 
.BR QuantLib .
