.\" Man page contributed by Luigi Ballabio
.\" and released under the Quantlib license
.TH Bonds 1 "22 October 2008" QuantLib
.SH NAME
Bonds - Example of bond pricing
.SH SYNOPSIS
.B Bonds
.SH DESCRIPTION
.PP
.B Bonds
is an example of using \fIQuantLib\fP.

It shows how to set up a term structure and then price some
simple bonds. The last part is dedicated to peripherical computations
such as yield-to-price or price-to-yield.

.SH SEE ALSO
The source code
.IR Bonds.cpp ,
.BR BermudanSwaption (1),
.BR CallableBonds (1),
.BR CDS (1),
.BR ConvertibleBonds (1),
.BR DiscreteHedging (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR MarketModels (1),
.BR Replication (1),
.BR Repo (1),
.BR SwapValuation (1),
the QuantLib documentation and website at
.IR http://quantlib.org .

.SH AUTHORS
The QuantLib Group (see
.IR Authors.txt ).

This manual page was added by Luigi Ballabio .
