.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH CallableBonds 1 "18 July 2008" QuantLib
.SH NAME
CallableBonds - Example of callable-bond pricing
.SH SYNOPSIS
.B CallableBonds
.SH DESCRIPTION
.PP
.B CallableBonds
is an example of using \fIQuantLib\fP.

It prices a number of callable bonds and compares the
results to known good data.

.SH SEE ALSO
The source code
.IR CallableBonds.cpp ,
.BR BermudanSwaption (1),
.BR Bonds (1),
.BR CDS (1),
.BR ConvertibleBonds (1),
.BR DiscreteHedging (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR MarketModels (1),
.BR Replication (1),
.BR Repo (1),
.BR SwapValuation (1),
the QuantLib documentation and website at
.IR http://quantlib.org .

.SH AUTHORS
The QuantLib Group (see
.IR Authors.txt ).

This manual page was added by Dirk Eddelbuettel <edd@debian.org>,
the Debian GNU/Linux maintainer for
.BR QuantLib .
