.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH EUROPEANOPTION 1 "20 September 2001" QuantLib
.SH NAME
EuropeanOption - Example of using QuantLib
.SH SYNOPSIS
.B EuropeanOption
.SH DESCRIPTION
.PP
.B EuropeanOption
is an example of using \fIQuantLib\fP.

It computes the value of a European Call option using six different methods.
.SH SEE ALSO
The source code 
.IR EuropeanOption.cpp ,
.BR DiscreteHedging (1),
.BR SwapValuation (1),
the QuantLib documentation and website at
.IR http://quantlib.org .

.SH AUTHORS
The QuantLib Group (see 
.IR Authors.txt ).

This manual page was added by Dirk Eddelbuettel
<edd@debian.org>, the Debian GNU/Linux maintainer for 
.BR QuantLib .
