.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH MarketModels 1 "13 January 2010" QuantLib
.SH NAME
MarketModels - Example of Monte Carlo pricing with market models
.SH SYNOPSIS
.B MarketModels
.SH DESCRIPTION
.PP
.B MarketModels
is an example of using \fIQuantLib\fP.

It prices a series of inverse floaters under market models using simulation.

.SH SEE ALSO
The source code
.IR MarketModels.cpp ,
.BR BermudanSwaption (1),
.BR Bonds (1),
.BR CallableBonds (1),
.BR CDS (1),
.BR ConvertibleBonds (1),
.BR DiscreteHedging (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR Replication (1),
.BR Repo (1),
.BR SwapValuation (1),
the QuantLib documentation and website at
.IR http://quantlib.org .

.SH AUTHORS
The QuantLib Group (see
.IR Authors.txt ).

This manual page was added by Dirk Eddelbuettel <edd@debian.org>,
the Debian GNU/Linux maintainer for
.BR QuantLib .
