.\" Man page contributed by Luigi Ballabio <ballabio@mac.com>
.\" and released under the Quantlib license
.TH MulticurveBootstrapping 1 "27 October 2018" QuantLib
.SH NAME
MulticurveBootstrapping - Example of using QuantLib
.SH SYNOPSIS
.B MulticurveBootstrapping
.SH DESCRIPTION
.PP
.B MulticurveBootstrapping
is an example of using \fIQuantLib\fP.

It prices an interest-rate swap over a bootstrapped term structure and
calculates its fair fixed rate and floating spread.
.SH SEE ALSO
The source code
.IR MulticurveBootstrapping.cpp ,
.BR BermudanSwaption (1),
.BR Bonds (1),
.BR CallableBonds (1),
.BR CDS (1),
.BR ConvertibleBonds (1),
.BR DiscreteHedging (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR MarketModels (1),
.BR Replication (1),
.BR Repo (1),
the QuantLib documentation and website at
.IR https://www.quantlib.org .

.SH AUTHORS
The QuantLib Group (see
.IR Contributors.txt ).

This manual page was added by Luigi Ballabio
<luigi.ballabio@gmail.com> .
