.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH QUANTLIB-TEST-SUITE 1 "27 July 2003" QuantLib
.SH NAME
quantlib-test-suite - test executable for QuantLib
.SH SYNOPSIS
.B quantlib-test-suite
.SH DESCRIPTION
.PP
.B quantlib-test-suite
is created at compile-time from the \fIQuantLib\fP sources using the
\fBoost test framework\fP tool.

It validates the compiled code against pre-constructed test cases, and helps
in validating the library.
.SH SEE ALSO
The source code in the
.I test-suite
directory of the
.I QuantLib
sources,
the QuantLib documentation and website at
.I http://quantlib.org
and the Boost documentation and website at
.IR http://www.boost.org .

.SH AUTHORS
The QuantLib Group (see
.IR Authors.txt ).

This manual page was added by Dirk Eddelbuettel <edd@debian.org>,
the Debian GNU/Linux maintainer for
.BR QuantLib .
