.\" Man page contributed by Luigi Ballabio <ballabio@mac.com>
.\" and released under the Quantlib license
.TH SWAPVALUATION 1 "20 September 2001" QuantLib
.SH NAME
SwapValuation - Example of using QuantLib
.SH SYNOPSIS
.B SwapValuation
.SH DESCRIPTION
.PP
.B SwapValuation
is an example of using \fIQuantLib\fP.

It prices an Interest Rate Swap over a term structure and calculates
its fair fixed rate and floating spread.
.SH SEE ALSO
The source code
.IR swapvaluation.cpp ,
.BR BermudanSwaption (1),
.BR Bonds (1),
.BR CallableBonds (1),
.BR CDS (1),
.BR ConvertibleBonds (1),
.BR DiscreteHedging (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR MarketModels (1),
.BR Replication (1),
.BR Repo (1),
the QuantLib documentation and website at
.IR http://quantlib.org .

.SH AUTHORS
The QuantLib Group (see
.IR Authors.txt ).

This manual page was added by Luigi Ballabio
<ballabio@mac.com> .
