/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/legacy/termstructures/compoundforward.hpp>
#include <ql/legacy/termstructures/extendeddiscountcurve.hpp>

