name:
  Setup
description:
  Setup of the needed software

inputs:
  os:
    description: The os for the run.
    required: true

  cxx:
    description: The c++ compiler to use.
    required: true

  cxx-standard:
    description: The c++ standard to use.
    required: true

runs:
  using: composite
  steps:
    - name: Determine ccache variant
      shell: bash
      run: |
        echo "CMAKE_CXX_COMPILER_LAUNCHER=${{ ( (runner.os == 'Windows') && 'sccache' ) || 'ccache' }}"   >> $GITHUB_ENV

    - name: Setup Linux variables
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"                             >> $GITHUB_PATH

    - name: Setup Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache ninja-build

        brew update
        brew install boost

    - name: Setup build variables on macOs
      if: runner.os == 'macOs'
      shell: bash
      run: |
        echo "CXXFLAGS=-stdlib=libc++"                                                                    >> $GITHUB_ENV
        echo "HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1"                                                   >> $GITHUB_ENV

    - name: Setup macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install ninja boost

    - name: Setup Windows variables
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write "BOOST_DOWNLOAD_URI=https://downloads.sourceforge.net/project/boost/boost-binaries/1.88.0/boost_1_88_0-msvc-14.3-64.exe"  >> $env:GITHUB_ENV
        Write "BOOST_INSTALLER_PATH=$env:RUNNER_TEMP\boost.exe"                                                                         >> $env:GITHUB_ENV
        Write "BOOST_INSTALL_DIR=$env:RUNNER_TEMP\boost"                                                                                >> $env:GITHUB_ENV
        Write "Boost_DIR=$env:RUNNER_TEMP\boost\lib64-msvc-14.3\cmake\Boost-1.88.0"                                                     >> $env:GITHUB_ENV

    - name: Setup Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Start-BitsTransfer -Source $env:BOOST_DOWNLOAD_URI -Destination $env:BOOST_INSTALLER_PATH
        Start-Process -Wait -FilePath "$env:BOOST_INSTALLER_PATH" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=$env:BOOST_INSTALL_DIR"

        choco install -y ninja

    - name: Set up Visual Studio shell on Windows
      uses: TheMrMilchmann/setup-msvc-dev@v3
      if: runner.os == 'Windows'
      with:
        arch: x64

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ inputs.os }}-${{ inputs.cxx }}--cxx-standard-${{ inputs.cxx-standard }}--${{ github.job }}
        restore-keys: |
          ${{ inputs.os }}-${{ inputs.cxx }}--cxx-standard-${{ inputs.cxx-standard }}--${{ github.job }}
          ${{ inputs.os }}-${{ inputs.cxx }}--cxx-standard-${{ inputs.cxx-standard }}
          ${{ inputs.os }}-${{ inputs.cxx }}
          ${{ inputs.os }}
        variant: ${{ env.CMAKE_CXX_COMPILER_LAUNCHER }}

