#undef QL_SQRT
#undef QL_FABS
#undef QL_EXP
#undef QL_LOG
#undef QL_SIN
#undef QL_COS
#undef QL_POW
#undef QL_MODF
#undef QL_STRLEN
#undef QL_TOLOWER
#undef QL_TOUPPER
#undef QL_CLOCK
#undef QL_MAX
#undef QL_MIN
#undef QL_MIN_INT
#undef QL_MAX_INT
#undef QL_MIN_DOUBLE
#undef QL_MAX_DOUBLE
#undef QL_EPSILON
#undef QL_HAS_LIMITS
#undef QL_HAS_CLIMITS
#undef QL_HAS_LIMITS_H
#undef QL_HAS_FLOAT_H
#undef QL_HAS_SSTREAM
#undef QL_HAS_STRSTREAM
#undef QL_HAS_CMATH
#undef QL_HAS_MATH_H
#undef QL_HAS_CCTYPE
#undef QL_HAS_CTYPE_H
#undef QL_HAS_CTIME
#undef QL_HAS_TIME_H
#undef QL_HAVE_NAMESPACES
#undef QL_USING_STD_MAP
#undef QL_USING_STD_STRING
#undef QL_ITERATOR
#undef QL_ITERATOR_TRAITS
#undef QL_RANDOM_ACCESS_ITERATOR_TAG
#undef PACKAGE

#undef VERSION
