/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatilities/swaptionvol/cmsmarket.hpp>
#include <ql/termstructures/volatilities/swaptionvol/spreadedswaptionvolstructure.hpp>
#include <ql/termstructures/volatilities/swaptionvol/swaptionconstantvol.hpp>
#include <ql/termstructures/volatilities/swaptionvol/swaptionvolcube.hpp>
#include <ql/termstructures/volatilities/swaptionvol/swaptionvolcube1.hpp>
#include <ql/termstructures/volatilities/swaptionvol/swaptionvolcube2.hpp>
#include <ql/termstructures/volatilities/swaptionvol/swaptionvoldiscrete.hpp>
#include <ql/termstructures/volatilities//swaptionvol/swaptionvolmatrix.hpp>

