/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatilities/caplet/capflatvolvector.hpp>
#include <ql/termstructures/volatilities/caplet/capletconstantvol.hpp>
#include <ql/termstructures/volatilities/caplet/capletvariancecurve.hpp>
#include <ql/termstructures/volatilities/caplet/capletvolatilitiesstructures.hpp>
#include <ql/termstructures/volatilities/caplet/capstripper.hpp>
#include <ql/termstructures/volatilities/caplet/spreadedcapletvolstructure.hpp>

