/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

/*
 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <https://www.quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

/*! \file splicedtermstructure.hpp
    \brief Yield term structure spliced from two curves at a switch date
*/

#ifndef quantlib_spliced_term_structure_hpp
#define quantlib_spliced_term_structure_hpp

#include <ql/termstructures/yieldtermstructure.hpp>
#include <ql/utilities/null.hpp>
#include <utility>

namespace QuantLib {

    //! Yield term structure generated by splicing two curves at a switch date
    /*! Discount factors are taken from the first curve up until
        the switch date and from the second curve beyond it. The
        second curve is renomalized by the discount factor at the
        switch date, so the discount factors are continuous.

        \note This term structure remains linked to both curves, i.e.,
              any change in either is reflected within this curve as well

        \ingroup yieldtermstructures
    */

    class SplicedYieldTermStructure : public YieldTermStructure {
        public:
          SplicedYieldTermStructure(Handle<YieldTermStructure> curve1,
                                    Handle<YieldTermStructure> curve2,
                                    const Date& switchDate);
          //! \name YieldTermStructure interface
          //@{
          DayCounter dayCounter() const override;
          Calendar calendar() const override;
          Natural settlementDays() const override;
          const Date& referenceDate() const override;
          Date maxDate() const override;
        protected:
          DiscountFactor discountImpl(Time) const override;
          //@}
          //! \name Observer interface
          //@{
          void update() override;
          //@}
        private:
          void setupExtrapolation();

          Handle<YieldTermStructure> curve1_;
          Handle<YieldTermStructure> curve2_;
          Date switchDate_;
          mutable Time switchTime_ = Null<Time>();
          mutable Time offset_ = Null<Time>();
          mutable Real anchor_ = Null<Real>();
    };


    // inline definitions

    inline SplicedYieldTermStructure::SplicedYieldTermStructure(Handle<YieldTermStructure> curve1,
                                                                Handle<YieldTermStructure> curve2,
                                                                const Date& switchDate)
    : curve1_(std::move(curve1)), curve2_(std::move(curve2)), switchDate_(switchDate) {
        registerWith(curve1_);
        registerWith(curve2_);
        setupExtrapolation();
    }

    inline void SplicedYieldTermStructure::setupExtrapolation() {
        if (!curve1_.empty() && !curve2_.empty())
            // We could have added (curve1_->maxDate() >= switchDate_) to the condition to make
            // it more precise, however, setupExtrapolation is called too early. Using maxDate
            // here would 1) trigger bootstrapping for Piecewise curves and 2) fail for Spreaded
            // curves whose originalCurve is not set yet
            enableExtrapolation(curve1_->allowsExtrapolation() && curve2_->allowsExtrapolation());
    }

    inline DayCounter SplicedYieldTermStructure::dayCounter() const {
        return curve1_->dayCounter();
    }

    inline Calendar SplicedYieldTermStructure::calendar() const {
        return curve1_->calendar();
    }

    inline Natural SplicedYieldTermStructure::settlementDays() const {
        return curve1_->settlementDays();
    }

    inline const Date& SplicedYieldTermStructure::referenceDate() const {
        return curve1_->referenceDate();
    }

    inline Date SplicedYieldTermStructure::maxDate() const {
        const Date firstMaxDate = curve1_->maxDate();
        return firstMaxDate < switchDate_ ? firstMaxDate
                                          : std::max(switchDate_, curve2_->maxDate());
    }

    inline void SplicedYieldTermStructure::update() {
        switchTime_ = Null<Time>();
        offset_ = Null<Time>();
        anchor_ = Null<Real>();
        setupExtrapolation();
        if (!curve1_.empty()) {
            YieldTermStructure::update();
        } else {
            // reference date is not available until both curves are set
            // NOLINTNEXTLINE(bugprone-parent-virtual-call)
            TermStructure::update();
        }
    }

    inline DiscountFactor SplicedYieldTermStructure::discountImpl(Time t) const {
        if (switchTime_ == Null<Time>()) {
            QL_REQUIRE(curve1_->dayCounter() == curve2_->dayCounter(),
                       "the two curves must have the same day counter");
            switchTime_ = timeFromReference(switchDate_);
            offset_ = timeFromReference(curve2_->referenceDate());
        }
        if (t <= switchTime_)
            return curve1_->discount(t, true);
        if (anchor_ == Null<Real>()) {
            anchor_ = curve1_->discount(switchTime_, true) /
                      curve2_->discount(switchTime_ - offset_, true);
        }
        return anchor_ * curve2_->discount(t - offset_, true);
    }

}


#endif
