.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH DISCRETEHEDGING 1 "20 September 2001" QuantLib
.SH NAME
DiscreteHedging - Example of using QuantLib
.SH SYNOPSIS
.B DiscreteHedging
.SH DESCRIPTION
.PP
.B DiscreteHedging
is an example of using the \fIQuantLib\fP Monte Carlo simulation framework.

By simulation,
.B DiscreteHedging
computes profit and loss of a discrete interval hedging
strategy and compares with the outcome with the results of Derman and Kamal's
Goldman Sachs Equity Derivatives Research Note "When You Cannot
Hedge Continuously: The Corrections to Black-Scholes".
.SH SEE ALSO
The source code
.IR DiscreteHedging.cpp ,
.BR BermudanSwaption (1),
.BR Bonds (1),
.BR CallableBonds (1),
.BR CDS (1),
.BR ConvertibleBonds (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR MarketModels (1),
.BR MulticurveBootstrapping (1),
.BR Replication (1),
.BR Repo (1),
the QuantLib documentation and website at
.IR https://www.quantlib.org ,
.I http://www.gs.com/qs/doc/when_you_cannot_hedge.pdf

.SH AUTHORS
The QuantLib Group (see
.IR Contributors.txt ).

This manual page was added by Dirk Eddelbuettel
<edd@debian.org>, the Debian GNU/Linux maintainer for
.BR QuantLib .
