.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the Quantlib license
.TH MULTIDIMINTEGRAL 1 "27 April 2016" QuantLib
.SH NAME
MultidimIntegral - Example of Multi-dimensional Numerical Integration
.SH SYNOPSIS
.B MultidimIntegral
.SH DESCRIPTION
.PP
.B MultidimIntegral
is an example of using \fIQuantLib\fP.

.SH SEE ALSO
The source code
.IR CDS.cpp ,
.BR BermudanSwaption (1),
.BR Bonds (1),
.BR CallableBonds (1),
.BR ConvertibleBonds (1),
.BR DiscreteHedging (1),
.BR EquityOption (1),
.BR FittedBondCurve (1),
.BR FRA (1),
.BR MarketModels (1),
.BR MulticurveBootstrapping (1),
.BR Replication (1),
.BR Repo (1),
the QuantLib documentation and website at
.IR https://www.quantlib.org .

.SH AUTHORS
The QuantLib Group (see
.IR Contributors.txt ).

This manual page was added by Dirk Eddelbuettel <edd@debian.org>,
the Debian GNU/Linux maintainer for
.BR QuantLib .
