/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/voltermstructures/interestrate/cap/capflatvolvector.hpp>
#include <ql/voltermstructures/interestrate/cap/capfloorvolatilitystructure.hpp>
#include <ql/voltermstructures/interestrate/cap/capvolsurface.hpp>

