/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/marketmodels/exercisevalues/bermudanswaptionexercisevalue.hpp>
#include <ql/marketmodels/exercisevalues/nothingexercisevalue.hpp>

