/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/inflation/capflooredinflationcoupon.hpp>
#include <ql/experimental/inflation/genericindexes.hpp>
#include <ql/experimental/inflation/inflationcappedcouponpricer.hpp>
#include <ql/experimental/inflation/inflationcoupon.hpp>
#include <ql/experimental/inflation/inflationcouponpricer.hpp>
#include <ql/experimental/inflation/nominalyoyinflationcoupon.hpp>
#include <ql/experimental/inflation/yoyoptionletvolatilitystructures.hpp>

