/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/inflation/capflooredinflationcoupon.hpp>
#include <ql/experimental/inflation/genericindexes.hpp>
#include <ql/experimental/inflation/inflationcapfloor.hpp>
#include <ql/experimental/inflation/inflationcapfloorengines.hpp>
#include <ql/experimental/inflation/inflationcappedcouponpricer.hpp>
#include <ql/experimental/inflation/inflationcoupon.hpp>
#include <ql/experimental/inflation/inflationcouponpricer.hpp>
#include <ql/experimental/inflation/interpolatedyoyoptionletstripper.hpp>
#include <ql/experimental/inflation/kinterpolatedyoyoptionletvolatilitysurface.hpp>
#include <ql/experimental/inflation/nominalyoyinflationcoupon.hpp>
#include <ql/experimental/inflation/piecewiseyoyoptionletvolatility.hpp>
#include <ql/experimental/inflation/polynomial2D.hpp>
#include <ql/experimental/inflation/polynomial2Dspline.hpp>
#include <ql/experimental/inflation/yoycapfloortermpricesurface.hpp>
#include <ql/experimental/inflation/yoyoptionlethelpers.hpp>
#include <ql/experimental/inflation/yoyoptionletstripper.hpp>
#include <ql/experimental/inflation/yoyoptionletvolatilitystructures.hpp>

