/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatility/interestrate/capfloor/capfloortermvolatilitystructure.hpp>
#include <ql/termstructures/volatility/interestrate/capfloor/capfloortermvolcurve.hpp>
#include <ql/termstructures/volatility/interestrate/capfloor/capfloortermvolsurface.hpp>

