/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/overnightswap/makeois.hpp>
#include <ql/experimental/overnightswap/overnightindexedcoupon.hpp>
#include <ql/experimental/overnightswap/overnightindexedswap.hpp>
#include <ql/experimental/overnightswap/oisratehelper.hpp>

