/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/overnightswap/eonia.hpp>
#include <ql/experimental/overnightswap/eoniacoupon.hpp>
#include <ql/experimental/overnightswap/eoniaswap.hpp>
#include <ql/experimental/overnightswap/eoniaswaphelper.hpp>

