/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatilities/capletvol/capflatvolvector.hpp>
#include <ql/termstructures/volatilities/capletvol/capletconstantvol.hpp>
#include <ql/termstructures/volatilities/capletvol/capletvariancecurve.hpp>
#include <ql/termstructures/volatilities/capletvol/capletvolatilitiesstructures.hpp>
#include <ql/termstructures/volatilities/capletvol/capstripper.hpp>

