/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/experimental/amortizingbonds/amortizingcmsratebond.hpp>
#include <ql/experimental/amortizingbonds/amortizingfixedratebond.hpp>
#include <ql/experimental/amortizingbonds/amortizingfloatingratebond.hpp>

