/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatilities/interpolatedsmilesection.hpp>
#include <ql/termstructures/volatilities/sabr.hpp>
#include <ql/termstructures/volatilities/sabrinterpolatedsmilesection.hpp>
#include <ql/termstructures/volatilities/smilesection.hpp>

#include <ql/termstructures/volatilities/equityfx/all.hpp>
#include <ql/termstructures/volatilities/interestrate/all.hpp>
