#!/bin/bash
# Copyright (C) 2003 RiskMap srl
#
# This file is part of QuantLib, a free-software/open-source library
# for financial quantitative analysts and developers - http://quantlib.org/
#
# QuantLib is free software: you can redistribute it and/or modify it under the
# terms of the QuantLib license.  You should have received a copy of the
# license along with this program; if not, please email
# quantlib-dev@lists.sf.net
# The license is also available online at http://quantlib.org/html/license.html
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the license for more details.
if test "$1" == "" ; then
echo usage: update_copyright YEAR ;
else
grep -r -I Copyright * | \
gawk 'BEGIN { FS = ":" } ; { print $1 }' | \
xargs -n1 bash -c "gawk '
BEGIN {
     year_pat = \"[0-9][0-9][0-9][0-9]\"
     full_pat = \"(\" year_pat \"-\" year_pat \")|(\" year_pat \"(, *\" year_pat \")*)\"
}

/Copyright/ {
     match(\$0,full_pat)
     if (RSTART) {
         old_range = substr(\$0,RSTART,RLENGTH)
         start = substr(\$0,RSTART,4)
         end =   substr(\$0,RSTART+RLENGTH-4,4)
         if (YEAR > end) {
             end = YEAR
             if (end-start >= 3) {
                 range = start \"-\" end
             } else {
                 range = start
                 while (start < end) {
                     range = range \", \" (++start)
                 }
             }
             sub(old_range,range)
         }
     }
}

{ print }
' YEAR=$1 \$0 > .temp.file ;
mv .temp.file \$0" ;
fi
