/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/bootstraphelper.hpp>
#include <ql/termstructures/bootstrapper.hpp>
#include <ql/termstructures/inflationtermstructure.hpp>
#include <ql/termstructures/voltermstructure.hpp>
#include <ql/termstructures/yieldtermstructure.hpp>

#include <ql/termstructures/inflation/all.hpp>
#include <ql/termstructures/volatility/all.hpp>
#include <ql/termstructures/yield/all.hpp>
