/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */


#include <ql/termstructures/yield/all.hpp>
#include <ql/termstructures/volatility/all.hpp>
