/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/voltermstructures/equityfx/blackconstantvol.hpp>
#include <ql/termstructures/voltermstructures/equityfx/blackvariancecurve.hpp>
#include <ql/termstructures/voltermstructures/equityfx/blackvariancesurface.hpp>
#include <ql/termstructures/voltermstructures/equityfx/impliedvoltermstructure.hpp>
#include <ql/termstructures/voltermstructures/equityfx/localconstantvol.hpp>
#include <ql/termstructures/voltermstructures/equityfx/localvolcurve.hpp>
#include <ql/termstructures/voltermstructures/equityfx/localvolsurface.hpp>

