/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/legacy/pricers/discretegeometricaso.hpp>
#include <ql/legacy/pricers/mccliquetoption.hpp>
#include <ql/legacy/pricers/mcdiscretearithmeticaso.hpp>
#include <ql/legacy/pricers/mcpagoda.hpp>
#include <ql/legacy/pricers/mcperformanceoption.hpp>
#include <ql/legacy/pricers/mcpricer.hpp>
#include <ql/legacy/pricers/singleassetoption.hpp>

