/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/processes/batesprocess.hpp>
#include <ql/processes/blackscholesprocess.hpp>
#include <ql/processes/coxingersollrossprocess.hpp>
#include <ql/processes/endeulerdiscretization.hpp>
#include <ql/processes/eulerdiscretization.hpp>
#include <ql/processes/forwardmeasureprocess.hpp>
#include <ql/processes/g2process.hpp>
#include <ql/processes/geometricbrownianprocess.hpp>
#include <ql/processes/gjrgarchprocess.hpp>
#include <ql/processes/gsrprocess.hpp>
#include <ql/processes/gsrprocesscore.hpp>
#include <ql/processes/hestonprocess.hpp>
#include <ql/processes/hestonslvprocess.hpp>
#include <ql/processes/hullwhiteprocess.hpp>
#include <ql/processes/hybridhestonhullwhiteprocess.hpp>
#include <ql/processes/jointstochasticprocess.hpp>
#include <ql/processes/merton76process.hpp>
#include <ql/processes/mfstateprocess.hpp>
#include <ql/processes/ornsteinuhlenbeckprocess.hpp>
#include <ql/processes/squarerootprocess.hpp>
#include <ql/processes/stochasticprocessarray.hpp>
