/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/volatilitymodels/constantestimator.hpp>
#include <ql/volatilitymodels/simplelocalestimator.hpp>
#include <ql/volatilitymodels/garmanklass.hpp>
#include <ql/volatilitymodels/garch.hpp>

