/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/voltermstructures/interestrate/capfloor/capfloortermvolvector.hpp>
#include <ql/voltermstructures/interestrate/capfloor/capfloortermvolatilitystructure.hpp>
#include <ql/voltermstructures/interestrate/capfloor/capfloortermvolsurface.hpp>

