from typing import Iterable, Sequence, overload

class Month:
    January: Month
    February: Month
    March: Month
    April: Month
    May: Month
    June: Month
    July: Month
    August: Month
    September: Month
    October: Month
    November: Month
    December: Month

class TimeUnit:
    Days: TimeUnit
    Weeks: TimeUnit
    Months: TimeUnit
    Years: TimeUnit

class Frequency:
    Annual: Frequency
    Semiannual: Frequency
    Quarterly: Frequency
    Monthly: Frequency

class BusinessDayConvention:
    Following: BusinessDayConvention
    ModifiedFollowing: BusinessDayConvention
    Preceding: BusinessDayConvention
    ModifiedPreceding: BusinessDayConvention
    Unadjusted: BusinessDayConvention

class DateGeneration:
    Backward: DateGeneration
    Forward: DateGeneration

class Compounding:
    Simple: Compounding
    Compounded: Compounding
    Continuous: Compounding

class OptionType:
    Put: OptionType
    Call: OptionType

class SwapType:
    Receiver: SwapType
    Payer: SwapType

class ActualActualConvention:
    ISDA: ActualActualConvention
    ISMA: ActualActualConvention
    Bond: ActualActualConvention

class Thirty360Convention:
    BondBasis: Thirty360Convention
    USA: Thirty360Convention
    European: Thirty360Convention

class UnitedStatesMarket:
    Settlement: UnitedStatesMarket
    NYSE: UnitedStatesMarket
    GovernmentBond: UnitedStatesMarket
    SOFR: UnitedStatesMarket

class Date:
    def __init__(self, day: int, month: Month, year: int) -> None: ...
    def day_of_month(self) -> int: ...
    def month(self) -> Month: ...
    def year(self) -> int: ...
    def serial_number(self) -> int: ...
    def __add__(self, other: int | Period) -> Date: ...
    def __sub__(self, other: int | Period) -> Date: ...

class Period:
    def __init__(self, n: int, units: TimeUnit) -> None: ...
    def __init__(self, frequency: Frequency) -> None: ...  # type: ignore[misc]
    def length(self) -> int: ...
    def units(self) -> TimeUnit: ...
    def frequency(self) -> Frequency: ...
    def __mul__(self, n: int) -> Period: ...

class Settings:
    @staticmethod
    def instance() -> Settings: ...
    evaluation_date: Date

class Quote:
    def value(self) -> float: ...
    def is_valid(self) -> bool: ...

class SimpleQuote(Quote):
    def __init__(self, value: float) -> None: ...
    def set_value(self, value: float) -> float: ...

class QuoteHandle:
    def __init__(self, value: Quote = ...) -> None: ...
    def empty(self) -> bool: ...
    def current_link(self) -> Quote: ...

class DayCounter:
    def name(self) -> str: ...
    def year_fraction(self, d1: Date, d2: Date) -> float: ...
    def day_count(self, d1: Date, d2: Date) -> int: ...

class Calendar:
    def name(self) -> str: ...
    def is_business_day(self, date: Date) -> bool: ...
    def is_holiday(self, date: Date) -> bool: ...
    def advance(
        self,
        date: Date,
        period: Period | int,
        convention: BusinessDayConvention = ...,
        end_of_month: bool = ...,
        unit: TimeUnit = ...,
    ) -> Date: ...
    def adjust(self, date: Date, convention: BusinessDayConvention = ...) -> Date: ...

class Schedule:
    def __init__(
        self,
        effective_date: Date,
        termination_date: Date,
        tenor: Period,
        calendar: Calendar,
        convention: BusinessDayConvention,
        termination_date_convention: BusinessDayConvention,
        rule: DateGeneration,
        end_of_month: bool,
    ) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> Date: ...
    def dates(self) -> list[Date]: ...
    def start_date(self) -> Date: ...
    def end_date(self) -> Date: ...

class InterestRate:
    def rate(self) -> float: ...
    def __float__(self) -> float: ...

class YieldTermStructureHandle:
    def empty(self) -> bool: ...
    def discount(self, date: Date, extrapolate: bool = ...) -> float: ...
    def reference_date(self) -> Date: ...
    def zero_rate(
        self,
        date: Date,
        day_counter: DayCounter,
        compounding: Compounding,
        frequency: Frequency = ...,
        extrapolate: bool = ...,
    ) -> InterestRate: ...

class RateHelper: ...

class IborIndex:
    def name(self) -> str: ...
    def tenor(self) -> Period: ...
    def fixing_calendar(self) -> Calendar: ...
    def day_counter(self) -> DayCounter: ...

class FixedRateBond:
    def __init__(
        self,
        settlement_days: int,
        face_amount: float,
        schedule: Schedule,
        coupons: Sequence[float],
        accrual_day_counter: DayCounter,
        payment_convention: BusinessDayConvention = ...,
        redemption: float = ...,
        issue_date: Date = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class VanillaSwap:
    def __init__(
        self,
        type: SwapType,
        nominal: float,
        fixed_schedule: Schedule,
        fixed_rate: float,
        fixed_day_count: DayCounter,
        float_schedule: Schedule,
        ibor_index: IborIndex,
        spread: float,
        floating_day_count: DayCounter,
    ) -> None: ...
    def NPV(self) -> float: ...
    def fair_rate(self) -> float: ...
    def fair_spread(self) -> float: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class EuropeanOption:
    def NPV(self) -> float: ...
    def set_pricing_engine(self, process: object) -> None: ...

def set_evaluation_date(date: Date) -> None: ...
def get_evaluation_date() -> Date: ...
def make_quote_handle(value: float) -> QuoteHandle: ...
def Actual365Fixed() -> DayCounter: ...
def Actual360() -> DayCounter: ...
def ActualActual(convention: ActualActualConvention = ...) -> DayCounter: ...
def Thirty360(convention: Thirty360Convention = ...) -> DayCounter: ...
def TARGET() -> Calendar: ...
def NullCalendar() -> Calendar: ...
def WeekendsOnly() -> Calendar: ...
def UnitedKingdom() -> Calendar: ...
def UnitedStates(market: UnitedStatesMarket = ...) -> Calendar: ...
def FlatForward(
    reference_date: Date, forward: float | QuoteHandle, day_counter: DayCounter
) -> YieldTermStructureHandle: ...
def DepositRateHelper(
    rate: float | QuoteHandle,
    tenor: Period,
    fixing_days: int,
    calendar: Calendar,
    convention: BusinessDayConvention,
    end_of_month: bool,
    day_counter: DayCounter,
) -> RateHelper: ...
def PiecewiseLogLinearDiscountCurve(
    reference_date: Date,
    helpers: Iterable[RateHelper],
    day_counter: DayCounter,
) -> YieldTermStructureHandle: ...
@overload
def Euribor3M() -> IborIndex: ...
@overload
def Euribor3M(handle: YieldTermStructureHandle) -> IborIndex: ...
@overload
def Euribor6M() -> IborIndex: ...
@overload
def Euribor6M(handle: YieldTermStructureHandle) -> IborIndex: ...

__version__: str
