from typing import Iterable, Sequence, overload

class Month:
    January: Month
    February: Month
    March: Month
    April: Month
    May: Month
    June: Month
    July: Month
    August: Month
    September: Month
    October: Month
    November: Month
    December: Month

class TimeUnit:
    Days: TimeUnit
    Weeks: TimeUnit
    Months: TimeUnit
    Years: TimeUnit

class Frequency:
    Annual: Frequency
    Semiannual: Frequency
    Quarterly: Frequency
    Monthly: Frequency

class BusinessDayConvention:
    Following: BusinessDayConvention
    ModifiedFollowing: BusinessDayConvention
    Preceding: BusinessDayConvention
    ModifiedPreceding: BusinessDayConvention
    Unadjusted: BusinessDayConvention

class DateGeneration:
    Backward: DateGeneration
    Forward: DateGeneration
    TwentiethIMM: DateGeneration
    CDS: DateGeneration
    CDS2015: DateGeneration

class ProtectionSide:
    Buyer: ProtectionSide
    Seller: ProtectionSide

class Compounding:
    Simple: Compounding
    Compounded: Compounding
    Continuous: Compounding

class OptionType:
    Put: OptionType
    Call: OptionType

class SwapType:
    Receiver: SwapType
    Payer: SwapType

class Position:
    Long: Position
    Short: Position

class BarrierType:
    DownIn: BarrierType
    UpIn: BarrierType
    DownOut: BarrierType
    UpOut: BarrierType

class DoubleBarrierType:
    KnockIn: DoubleBarrierType
    KnockOut: DoubleBarrierType
    KIKO: DoubleBarrierType
    KOKI: DoubleBarrierType

class AverageType:
    Arithmetic: AverageType
    Geometric: AverageType

class CdsPricingModel:
    Midpoint: CdsPricingModel
    ISDA: CdsPricingModel

class CapFloorType:
    Cap: CapFloorType
    Floor: CapFloorType
    Collar: CapFloorType

class ActualActualConvention:
    ISDA: ActualActualConvention
    ISMA: ActualActualConvention
    Bond: ActualActualConvention

class Thirty360Convention:
    BondBasis: Thirty360Convention
    USA: Thirty360Convention
    European: Thirty360Convention

class UnitedStatesMarket:
    Settlement: UnitedStatesMarket
    NYSE: UnitedStatesMarket
    GovernmentBond: UnitedStatesMarket
    SOFR: UnitedStatesMarket

class GermanyMarket:
    Settlement: GermanyMarket
    FrankfurtStockExchange: GermanyMarket
    Xetra: GermanyMarket
    Eurex: GermanyMarket
    Euwax: GermanyMarket

class SettlementType:
    Physical: SettlementType
    Cash: SettlementType

class SettlementMethod:
    PhysicalOTC: SettlementMethod
    PhysicalCleared: SettlementMethod
    CollateralizedCashPrice: SettlementMethod
    ParYieldCurve: SettlementMethod

class Date:
    def __init__(self, day: int, month: Month, year: int) -> None: ...
    def day_of_month(self) -> int: ...
    def month(self) -> Month: ...
    def year(self) -> int: ...
    def serial_number(self) -> int: ...
    def __add__(self, other: int | Period) -> Date: ...
    def __sub__(self, other: int | Period) -> Date: ...

class Period:
    def __init__(self, n: int, units: TimeUnit) -> None: ...
    def __init__(self, frequency: Frequency) -> None: ...  # type: ignore[misc]
    def length(self) -> int: ...
    def units(self) -> TimeUnit: ...
    def frequency(self) -> Frequency: ...
    def __mul__(self, n: int) -> Period: ...

class Settings:
    @staticmethod
    def instance() -> Settings: ...
    evaluation_date: Date
    include_todays_cash_flows: bool | None

class Quote:
    def value(self) -> float: ...
    def is_valid(self) -> bool: ...

class SimpleQuote(Quote):
    def __init__(self, value: float) -> None: ...
    def set_value(self, value: float) -> float: ...

class QuoteHandle:
    def __init__(self, value: Quote = ...) -> None: ...
    def empty(self) -> bool: ...
    def current_link(self) -> Quote: ...

class DayCounter:
    def name(self) -> str: ...
    def year_fraction(self, d1: Date, d2: Date) -> float: ...
    def day_count(self, d1: Date, d2: Date) -> int: ...

class Calendar:
    def name(self) -> str: ...
    def is_business_day(self, date: Date) -> bool: ...
    def is_holiday(self, date: Date) -> bool: ...
    def advance(
        self,
        date: Date,
        period: Period | int,
        convention: BusinessDayConvention = ...,
        end_of_month: bool = ...,
        unit: TimeUnit = ...,
    ) -> Date: ...
    def adjust(self, date: Date, convention: BusinessDayConvention = ...) -> Date: ...

class Schedule:
    def __init__(
        self,
        effective_date: Date,
        termination_date: Date,
        tenor: Period,
        calendar: Calendar,
        convention: BusinessDayConvention,
        termination_date_convention: BusinessDayConvention,
        rule: DateGeneration,
        end_of_month: bool,
    ) -> None: ...
    def __init__(  # type: ignore[misc]
        self,
        dates: Sequence[Date],
        calendar: Calendar = ...,
        convention: BusinessDayConvention = ...,
    ) -> None: ...
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> Date: ...
    def dates(self) -> list[Date]: ...
    def start_date(self) -> Date: ...
    def end_date(self) -> Date: ...

class InterestRate:
    def rate(self) -> float: ...
    def __float__(self) -> float: ...

class YieldTermStructureHandle:
    def empty(self) -> bool: ...
    def discount(self, date: Date, extrapolate: bool = ...) -> float: ...
    def reference_date(self) -> Date: ...
    def zero_rate(
        self,
        date: Date,
        day_counter: DayCounter,
        compounding: Compounding,
        frequency: Frequency = ...,
        extrapolate: bool = ...,
    ) -> InterestRate: ...

class RateHelper: ...

class IborIndex:
    def name(self) -> str: ...
    def tenor(self) -> Period: ...
    def fixing_calendar(self) -> Calendar: ...
    def day_counter(self) -> DayCounter: ...
    def fixing_days(self) -> int: ...
    def add_fixing(
        self, fixing_date: Date, fixing: float, force_overwrite: bool = ...
    ) -> None: ...
    def fixing(
        self, fixing_date: Date, forecast_todays_fixing: bool = ...
    ) -> float: ...

class OvernightIndex:
    def name(self) -> str: ...
    def tenor(self) -> Period: ...
    def fixing_calendar(self) -> Calendar: ...
    def day_counter(self) -> DayCounter: ...
    def fixing_days(self) -> int: ...
    def add_fixing(
        self, fixing_date: Date, fixing: float, force_overwrite: bool = ...
    ) -> None: ...
    def fixing(
        self, fixing_date: Date, forecast_todays_fixing: bool = ...
    ) -> float: ...

class FixedRateBond:
    def __init__(
        self,
        settlement_days: int,
        face_amount: float,
        schedule: Schedule,
        coupons: Sequence[float],
        accrual_day_counter: DayCounter,
        payment_convention: BusinessDayConvention = ...,
        redemption: float = ...,
        issue_date: Date = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class ZeroCouponBond:
    def __init__(
        self,
        settlement_days: int,
        calendar: Calendar,
        face_amount: float,
        maturity_date: Date,
        payment_convention: BusinessDayConvention = ...,
        redemption: float = ...,
        issue_date: Date = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def settlement_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class FloatingRateBond:
    def __init__(
        self,
        settlement_days: int,
        face_amount: float,
        schedule: Schedule,
        ibor_index: IborIndex,
        accrual_day_counter: DayCounter,
        payment_convention: BusinessDayConvention = ...,
        fixing_days: int = ...,
        gearings: Sequence[float] = ...,
        spreads: Sequence[float] = ...,
        caps: Sequence[float] = ...,
        floors: Sequence[float] = ...,
        in_arrears: bool = ...,
        redemption: float = ...,
        issue_date: Date = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def settlement_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class VanillaSwap:
    def __init__(
        self,
        type: SwapType,
        nominal: float,
        fixed_schedule: Schedule,
        fixed_rate: float,
        fixed_day_count: DayCounter,
        float_schedule: Schedule,
        ibor_index: IborIndex,
        spread: float,
        floating_day_count: DayCounter,
    ) -> None: ...
    def NPV(self) -> float: ...
    def fair_rate(self) -> float: ...
    def fair_spread(self) -> float: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class EuropeanExercise:
    def __init__(self, date: Date) -> None: ...
    def last_date(self) -> Date: ...

class AmericanExercise:
    def __init__(
        self,
        earliest_date: Date,
        latest_date: Date,
        payoff_at_expiry: bool = ...,
    ) -> None: ...
    def __init__(self, latest_date: Date, payoff_at_expiry: bool = ...) -> None: ...  # type: ignore[misc]
    def last_date(self) -> Date: ...

class PlainVanillaPayoff:
    def __init__(self, type: OptionType, strike: float) -> None: ...
    def strike(self) -> float: ...
    def option_type(self) -> OptionType: ...

class CashOrNothingPayoff:
    def __init__(
        self, type: OptionType, strike: float, cash_payoff: float
    ) -> None: ...
    def strike(self) -> float: ...
    def option_type(self) -> OptionType: ...
    def cash_payoff(self) -> float: ...

class FloatingTypePayoff:
    def __init__(self, type: OptionType) -> None: ...
    def option_type(self) -> OptionType: ...

class BlackScholesMertonProcess:
    def __init__(
        self,
        x0: QuoteHandle,
        dividend_ts: YieldTermStructureHandle,
        risk_free_ts: YieldTermStructureHandle,
        black_vol_ts: object,
    ) -> None: ...

class EuropeanOption:
    def __init__(
        self, payoff: PlainVanillaPayoff, exercise: EuropeanExercise
    ) -> None: ...
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def vega(self) -> float: ...
    def implied_volatility(
        self,
        target_price: float,
        process: BlackScholesMertonProcess,
        accuracy: float = ...,
        max_evaluations: int = ...,
        min_vol: float = ...,
        max_vol: float = ...,
    ) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...
    def set_mc_pricing_engine(
        self,
        process: BlackScholesMertonProcess,
        time_steps: int,
        required_samples: int,
        seed: int = ...,
        antithetic: bool = ...,
        brownian_bridge: bool = ...,
    ) -> None: ...

class VanillaOption:
    def __init__(
        self, payoff: PlainVanillaPayoff, exercise: AmericanExercise
    ) -> None: ...
    def __init__(
        self, payoff: PlainVanillaPayoff, exercise: EuropeanExercise
    ) -> None: ...  # type: ignore[misc]
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def vega(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...
    def set_binomial_pricing_engine(
        self, process: BlackScholesMertonProcess, steps: int = ...
    ) -> None: ...
    def set_fd_pricing_engine(
        self,
        process: BlackScholesMertonProcess,
        t_grid: int = ...,
        x_grid: int = ...,
        damping_steps: int = ...,
    ) -> None: ...

class OvernightIndexedSwap:
    def NPV(self) -> float: ...
    def fair_rate(self) -> float: ...
    def fair_spread(self) -> float: ...
    def fixed_leg_NPV(self) -> float: ...
    def overnight_leg_NPV(self) -> float: ...
    def set_pricing_engine(self, discount_curve: YieldTermStructureHandle) -> None: ...

class ForwardRateAgreement:
    def __init__(
        self,
        index: IborIndex,
        value_date: Date,
        type: Position,
        strike_forward_rate: float,
        notional_amount: float,
        discount_curve: YieldTermStructureHandle = ...,
    ) -> None: ...
    def __init__(
        self,
        index: IborIndex,
        value_date: Date,
        maturity_date: Date,
        type: Position,
        strike_forward_rate: float,
        notional_amount: float,
        discount_curve: YieldTermStructureHandle = ...,
    ) -> None: ...  # type: ignore[misc]
    def NPV(self) -> float: ...
    def amount(self) -> float: ...
    def forward_rate(self) -> InterestRate: ...
    def fixing_date(self) -> Date: ...

class BarrierOption:
    def __init__(
        self,
        barrier_type: BarrierType,
        barrier: float,
        rebate: float,
        payoff: PlainVanillaPayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def vega(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...

class DoubleBarrierOption:
    @overload
    def __init__(
        self,
        barrier_type: DoubleBarrierType,
        barrier_lo: float,
        barrier_hi: float,
        rebate: float,
        payoff: PlainVanillaPayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    @overload
    def __init__(
        self,
        barrier_type: DoubleBarrierType,
        barrier_lo: float,
        barrier_hi: float,
        rebate: float,
        payoff: CashOrNothingPayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    @overload
    def __init__(
        self,
        barrier_type: DoubleBarrierType,
        barrier_lo: float,
        barrier_hi: float,
        rebate: float,
        payoff: CashOrNothingPayoff,
        exercise: AmericanExercise,
    ) -> None: ...
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def vega(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...
    def set_binary_pricing_engine(
        self, process: BlackScholesMertonProcess
    ) -> None: ...

class CapFloor:
    def __init__(
        self,
        type: CapFloorType,
        schedule: Schedule,
        index: IborIndex,
        strike: float,
        nominal: float = ...,
        fixing_days: int = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def atm_rate(self, discount_curve: YieldTermStructureHandle) -> float: ...
    def start_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def type(self) -> CapFloorType: ...
    def set_pricing_engine(
        self,
        discount_curve: YieldTermStructureHandle,
        volatility: float,
        day_counter: DayCounter = ...,
        displacement: float = ...,
    ) -> None: ...

class BermudanExercise:
    def __init__(
        self, dates: Sequence[Date], payoff_at_expiry: bool = ...
    ) -> None: ...
    def dates(self) -> list[Date]: ...
    def last_date(self) -> Date: ...

class HullWhite:
    def __init__(
        self,
        term_structure: YieldTermStructureHandle,
        a: float = ...,
        sigma: float = ...,
    ) -> None: ...

class DefaultProbabilityTermStructureHandle:
    def empty(self) -> bool: ...
    def survival_probability(
        self, date: Date | float, extrapolate: bool = ...
    ) -> float: ...
    def hazard_rate(self, date: Date, extrapolate: bool = ...) -> float: ...
    def default_probability(
        self, date: Date, extrapolate: bool = ...
    ) -> float: ...
    def reference_date(self) -> Date: ...
    def max_date(self) -> Date: ...

class IsdaCdsNumericalFix:
    None: IsdaCdsNumericalFix
    Taylor: IsdaCdsNumericalFix

class IsdaCdsAccrualBias:
    HalfDayBias: IsdaCdsAccrualBias
    NoBias: IsdaCdsAccrualBias

class IsdaCdsForwardsInCouponPeriod:
    Flat: IsdaCdsForwardsInCouponPeriod
    Piecewise: IsdaCdsForwardsInCouponPeriod

class Gsr:
    @overload
    def __init__(
        self,
        term_structure: YieldTermStructureHandle,
        vol_step_dates: Sequence[Date],
        volatilities: Sequence[float],
        reversion: float,
        T: float = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        term_structure: YieldTermStructureHandle,
        vol_step_dates: Sequence[Date],
        volatilities: Sequence[float],
        reversions: Sequence[float],
        T: float = ...,
    ) -> None: ...
    def zerobond(
        self, maturity: float, t: float = ..., y: float = ...
    ) -> float: ...
    def numeraire_time(self) -> float: ...

class CreditDefaultSwap:
    def __init__(
        self,
        side: ProtectionSide,
        notional: float,
        spread: float,
        schedule: Schedule,
        payment_convention: BusinessDayConvention,
        day_counter: DayCounter,
        settles_accrual: bool = ...,
        pays_at_default_time: bool = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def fair_spread(self) -> float: ...
    def fair_upfront(self) -> float: ...
    def coupon_leg_NPV(self) -> float: ...
    def default_leg_NPV(self) -> float: ...
    def side(self) -> ProtectionSide: ...
    def notional(self) -> float: ...
    def running_spread(self) -> float: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self,
        probability: DefaultProbabilityTermStructureHandle,
        recovery_rate: float,
        discount_curve: YieldTermStructureHandle,
    ) -> None: ...
    def set_isda_pricing_engine(
        self,
        probability: DefaultProbabilityTermStructureHandle,
        recovery_rate: float,
        discount_curve: YieldTermStructureHandle,
        numerical_fix: IsdaCdsNumericalFix = ...,
        accrual_bias: IsdaCdsAccrualBias = ...,
        forwards_in_coupon_period: IsdaCdsForwardsInCouponPeriod = ...,
    ) -> None: ...

class Swaption:
    @overload
    def __init__(
        self,
        swap: VanillaSwap,
        exercise: EuropeanExercise,
        delivery: SettlementType = ...,
        settlement_method: SettlementMethod = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        swap: VanillaSwap,
        exercise: BermudanExercise,
        delivery: SettlementType = ...,
        settlement_method: SettlementMethod = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def type(self) -> SwapType: ...
    def settlement_type(self) -> SettlementType: ...
    def settlement_method(self) -> SettlementMethod: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self,
        discount_curve: YieldTermStructureHandle,
        volatility: float,
        day_counter: DayCounter = ...,
        displacement: float = ...,
    ) -> None: ...
    def set_tree_pricing_engine(
        self, model: HullWhite, time_steps: int = ...
    ) -> None: ...
    def set_jamshidian_pricing_engine(self, model: HullWhite) -> None: ...
    def set_gaussian1d_pricing_engine(
        self,
        model: Gsr,
        integration_points: int = ...,
        stddevs: float = ...,
        extrapolate_payoff: bool = ...,
        flat_payoff_extrapolation: bool = ...,
    ) -> None: ...
    def set_fd_hullwhite_pricing_engine(
        self,
        model: HullWhite,
        t_grid: int = ...,
        x_grid: int = ...,
        damping_steps: int = ...,
    ) -> None: ...

class ContinuousAveragingAsianOption:
    def __init__(
        self,
        average_type: AverageType,
        payoff: PlainVanillaPayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...

class DiscreteAveragingAsianOption:
    def __init__(
        self,
        average_type: AverageType,
        running_accumulator: float,
        past_fixings: int,
        fixing_dates: Sequence[Date],
        payoff: PlainVanillaPayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    def NPV(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...

class DefaultProbabilityHelper: ...

def set_evaluation_date(date: Date) -> None: ...
def get_evaluation_date() -> Date: ...
def make_quote_handle(value: float) -> QuoteHandle: ...
def make_vanilla_swap(
    swap_tenor: Period,
    index: IborIndex,
    fixed_rate: float,
    effective_date: Date,
    fixed_leg_tenor: Period = ...,
    fixed_day_count: DayCounter = ...,
    type: SwapType = ...,
    nominal: float = ...,
    floating_spread: float = ...,
) -> VanillaSwap: ...
def make_ois(
    swap_tenor: Period,
    overnight_index: OvernightIndex,
    fixed_rate: float,
    forward_start: Period = ...,
    type: SwapType = ...,
    nominal: float = ...,
    overnight_spread: float = ...,
) -> OvernightIndexedSwap: ...
def discount_times(
    curve_handle: YieldTermStructureHandle,
    times: object,
    extrapolate: bool = ...,
) -> object: ...
def discount_dates(
    curve_handle: YieldTermStructureHandle,
    dates: Sequence[Date],
    extrapolate: bool = ...,
) -> object: ...
def BlackSwaptionEngine(
    discount_curve: YieldTermStructureHandle,
) -> YieldTermStructureHandle: ...
def AnalyticEuropeanEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def BaroneAdesiWhaleyEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def AnalyticBarrierEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def AnalyticDoubleBarrierEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def AnalyticDoubleBarrierBinaryEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...

class ContinuousFloatingLookbackOption:
    def __init__(
        self,
        current_minmax: float,
        payoff: FloatingTypePayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...

class ContinuousFixedLookbackOption:
    def __init__(
        self,
        current_minmax: float,
        payoff: PlainVanillaPayoff,
        exercise: EuropeanExercise,
    ) -> None: ...
    def NPV(self) -> float: ...
    def delta(self) -> float: ...
    def gamma(self) -> float: ...
    def set_pricing_engine(self, process: BlackScholesMertonProcess) -> None: ...

def AnalyticContinuousFloatingLookbackEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def AnalyticContinuousFixedLookbackEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def BlackConstantVol(
    reference_date: Date,
    calendar: Calendar,
    volatility: float,
    day_counter: DayCounter,
) -> object: ...
def make_cap(
    tenor: Period,
    index: IborIndex,
    strike: float,
    nominal: float = ...,
    forward_start: Period = ...,
) -> CapFloor: ...
def make_floor(
    tenor: Period,
    index: IborIndex,
    strike: float,
    nominal: float = ...,
    forward_start: Period = ...,
) -> CapFloor: ...
def BlackCapFloorEngine(
    discount_curve: YieldTermStructureHandle,
    volatility: float,
    day_counter: DayCounter = ...,
    displacement: float = ...,
) -> YieldTermStructureHandle: ...
def simulate_gbm_paths(
    process: BlackScholesMertonProcess,
    length: float,
    time_steps: int,
    samples: int,
    seed: int = ...,
) -> object: ...
def Actual365Fixed() -> DayCounter: ...
def Actual360() -> DayCounter: ...
def ActualActual(convention: ActualActualConvention = ...) -> DayCounter: ...
def Thirty360(convention: Thirty360Convention = ...) -> DayCounter: ...
def TARGET() -> Calendar: ...
def NullCalendar() -> Calendar: ...
def WeekendsOnly() -> Calendar: ...
def UnitedKingdom() -> Calendar: ...
def Japan() -> Calendar: ...
def Germany(market: GermanyMarket = ...) -> Calendar: ...
def UnitedStates(market: UnitedStatesMarket = ...) -> Calendar: ...
def FlatForward(
    reference_date: Date, forward: float | QuoteHandle, day_counter: DayCounter
) -> YieldTermStructureHandle: ...
@overload
def FlatHazardRate(
    reference_date: Date, hazard_rate: float, day_counter: DayCounter
) -> DefaultProbabilityTermStructureHandle: ...
@overload
def FlatHazardRate(
    settlement_days: int,
    calendar: Calendar,
    hazard_rate: float,
    day_counter: DayCounter,
) -> DefaultProbabilityTermStructureHandle: ...
def InterpolatedHazardRateCurve(
    dates: Sequence[Date],
    hazard_rates: Sequence[float],
    day_counter: DayCounter,
    calendar: Calendar = ...,
) -> DefaultProbabilityTermStructureHandle: ...
def SpreadCdsHelper(
    running_spread: float,
    tenor: Period,
    settlement_days: int,
    calendar: Calendar,
    frequency: Frequency,
    payment_convention: BusinessDayConvention,
    rule: DateGeneration,
    day_counter: DayCounter,
    recovery_rate: float,
    discount_curve: YieldTermStructureHandle,
    settles_accrual: bool = ...,
    pays_at_default_time: bool = ...,
    model: CdsPricingModel = ...,
) -> DefaultProbabilityHelper: ...
def PiecewiseHazardRateCurve(
    reference_date: Date,
    helpers: Sequence[DefaultProbabilityHelper],
    day_counter: DayCounter,
) -> DefaultProbabilityTermStructureHandle: ...
def MidPointCdsEngine(
    probability: DefaultProbabilityTermStructureHandle,
) -> DefaultProbabilityTermStructureHandle: ...
def IsdaCdsEngine(
    probability: DefaultProbabilityTermStructureHandle,
) -> DefaultProbabilityTermStructureHandle: ...
def TreeSwaptionEngine(model: HullWhite) -> HullWhite: ...
def Gaussian1dSwaptionEngine(model: Gsr) -> Gsr: ...
def FdHullWhiteSwaptionEngine(model: HullWhite) -> HullWhite: ...
def AnalyticContinuousGeometricAveragePriceAsianEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def AnalyticDiscreteGeometricAveragePriceAsianEngine(
    process: BlackScholesMertonProcess,
) -> BlackScholesMertonProcess: ...
def uniform_1d_mesher_locations(
    start: float, end: float, size: int
) -> object: ...
def fdm_black_scholes_mesher_locations(
    size: int,
    process: BlackScholesMertonProcess,
    maturity: float,
    strike: float,
) -> object: ...
def fdm_black_scholes_values(
    process: BlackScholesMertonProcess,
    strike: float,
    maturity: float,
    option_type: OptionType = ...,
    t_grid: int = ...,
    x_grid: int = ...,
    damping_steps: int = ...,
) -> object: ...
def DepositRateHelper(
    rate: float | QuoteHandle,
    tenor: Period,
    fixing_days: int,
    calendar: Calendar,
    convention: BusinessDayConvention,
    end_of_month: bool,
    day_counter: DayCounter,
) -> RateHelper: ...
def FraRateHelper(
    rate: float | QuoteHandle,
    months_to_start: int,
    months_to_end: int = ...,
    fixing_days: int = ...,
    calendar: Calendar = ...,
    convention: BusinessDayConvention = ...,
    end_of_month: bool = ...,
    day_counter: DayCounter = ...,
) -> RateHelper: ...
@overload
def FraRateHelper(
    rate: QuoteHandle,
    months_to_start: int,
    ibor_index: IborIndex,
) -> RateHelper: ...
def SwapRateHelper(
    rate: float | QuoteHandle,
    tenor: Period,
    calendar: Calendar,
    fixed_frequency: Frequency,
    fixed_convention: BusinessDayConvention,
    fixed_day_count: DayCounter,
    ibor_index: IborIndex,
) -> RateHelper: ...
def PiecewiseLogLinearDiscountCurve(
    reference_date: Date,
    helpers: Iterable[RateHelper],
    day_counter: DayCounter,
) -> YieldTermStructureHandle: ...
@overload
def Euribor3M() -> IborIndex: ...
@overload
def Euribor3M(handle: YieldTermStructureHandle) -> IborIndex: ...
@overload
def Euribor6M() -> IborIndex: ...
@overload
def Euribor6M(handle: YieldTermStructureHandle) -> IborIndex: ...
@overload
def Sofr() -> OvernightIndex: ...
@overload
def Sofr(handle: YieldTermStructureHandle) -> OvernightIndex: ...
@overload
def Estr() -> OvernightIndex: ...
@overload
def Estr(handle: YieldTermStructureHandle) -> OvernightIndex: ...
@overload
def Eonia() -> OvernightIndex: ...
@overload
def Eonia(handle: YieldTermStructureHandle) -> OvernightIndex: ...

class YieldCurveModel:
    Standard: YieldCurveModel
    ExactYield: YieldCurveModel
    ParallelShifts: YieldCurveModel
    NonParallelShifts: YieldCurveModel

class VolatilityType:
    ShiftedLognormal: VolatilityType
    Normal: VolatilityType

class SwapIndex:
    def name(self) -> str: ...
    def tenor(self) -> Period: ...
    def fixing_days(self) -> int: ...
    def fixing_calendar(self) -> Calendar: ...
    def day_counter(self) -> DayCounter: ...
    def add_fixing(
        self, fixing_date: Date, fixing: float, force_overwrite: bool = ...
    ) -> None: ...
    def fixing(self, fixing_date: Date, forecast_today: bool = ...) -> float: ...
    def value_date(self, fixing_date: Date) -> Date: ...

class SwapSpreadIndex:
    def name(self) -> str: ...
    def fixing_days(self) -> int: ...
    def fixing_calendar(self) -> Calendar: ...
    def day_counter(self) -> DayCounter: ...
    def gearing1(self) -> float: ...
    def gearing2(self) -> float: ...
    def swap_index1(self) -> SwapIndex: ...
    def swap_index2(self) -> SwapIndex: ...
    def fixing(self, fixing_date: Date, forecast_today: bool = ...) -> float: ...
    def value_date(self, fixing_date: Date) -> Date: ...

class SwaptionVolatilityStructureHandle:
    def empty(self) -> bool: ...
    def volatility(
        self,
        option_date: Date,
        swap_tenor: Period,
        strike: float,
        extrapolate: bool = ...,
    ) -> float: ...

class CmsCouponPricer: ...

class CmsCoupon:
    def __init__(
        self,
        payment_date: Date,
        nominal: float,
        start_date: Date,
        end_date: Date,
        fixing_days: int,
        index: SwapIndex,
        gearing: float = ...,
        spread: float = ...,
        ref_period_start: Date = ...,
        ref_period_end: Date = ...,
        day_counter: DayCounter = ...,
        is_in_arrears: bool = ...,
    ) -> None: ...
    def rate(self) -> float: ...
    def amount(self) -> float: ...
    def nominal(self) -> float: ...
    def accrual_start_date(self) -> Date: ...
    def accrual_end_date(self) -> Date: ...
    def set_pricer(self, pricer: CmsCouponPricer) -> None: ...

class Swap:
    def NPV(self) -> float: ...
    def is_expired(self) -> bool: ...
    def number_of_legs(self) -> int: ...
    def set_pricing_engine(
        self, discount_curve: YieldTermStructureHandle
    ) -> None: ...
    def set_cms_coupon_pricer(self, pricer: CmsCouponPricer) -> None: ...

@overload
def EuriborSwapIsdaFixA(
    tenor: Period, handle: YieldTermStructureHandle = ...
) -> SwapIndex: ...
@overload
def EuriborSwapIsdaFixA(
    tenor: Period,
    forwarding: YieldTermStructureHandle,
    discounting: YieldTermStructureHandle,
) -> SwapIndex: ...
def ConstantSwaptionVolatility(
    reference_date: Date,
    calendar: Calendar,
    bdc: BusinessDayConvention,
    volatility: float,
    day_counter: DayCounter,
    type: VolatilityType = ...,
    shift: float = ...,
) -> SwaptionVolatilityStructureHandle: ...
def AnalyticHaganPricer(
    swaption_vol: SwaptionVolatilityStructureHandle,
    model: YieldCurveModel,
    mean_reversion: QuoteHandle,
) -> CmsCouponPricer: ...
def NumericHaganPricer(
    swaption_vol: SwaptionVolatilityStructureHandle,
    model: YieldCurveModel,
    mean_reversion: QuoteHandle,
    lower_limit: float = ...,
    upper_limit: float = ...,
    precision: float = ...,
) -> CmsCouponPricer: ...
def make_cms(
    swap_tenor: Period,
    swap_index: SwapIndex,
    ibor_index: IborIndex,
    ibor_spread: float = ...,
    forward_start: Period = ...,
    discount_curve: YieldTermStructureHandle = ...,
    pricer: CmsCouponPricer | None = ...,
    nominal: float = ...,
) -> Swap: ...
def make_swap_spread_index(
    family_name: str,
    swap_index1: SwapIndex,
    swap_index2: SwapIndex,
    gearing1: float = ...,
    gearing2: float = ...,
) -> SwapSpreadIndex: ...
def LinearTsrPricer(
    swaption_vol: SwaptionVolatilityStructureHandle,
    mean_reversion: QuoteHandle,
    coupon_discount_curve: YieldTermStructureHandle = ...,
) -> CmsCouponPricer: ...
class CmsSpreadCouponPricer: ...
def LognormalCmsSpreadPricer(
    cms_pricer: CmsCouponPricer,
    correlation: QuoteHandle,
    coupon_discount_curve: YieldTermStructureHandle = ...,
    integration_points: int = ...,
) -> CmsSpreadCouponPricer: ...
class CmsSpreadCoupon:
    def __init__(
        self,
        payment_date: Date,
        nominal: float,
        start_date: Date,
        end_date: Date,
        fixing_days: int,
        index: SwapSpreadIndex,
        gearing: float = ...,
        spread: float = ...,
        ref_period_start: Date = ...,
        ref_period_end: Date = ...,
        day_counter: DayCounter = ...,
        is_in_arrears: bool = ...,
    ) -> None: ...
    def rate(self) -> float: ...
    def amount(self) -> float: ...
    def fixing_date(self) -> Date: ...
    def set_pricer(self, pricer: CmsSpreadCouponPricer) -> None: ...
class CappedFlooredCmsSpreadCoupon:
    def __init__(
        self,
        payment_date: Date,
        nominal: float,
        start_date: Date,
        end_date: Date,
        fixing_days: int,
        index: SwapSpreadIndex,
        gearing: float = ...,
        spread: float = ...,
        cap: float | None = ...,
        floor: float | None = ...,
        ref_period_start: Date = ...,
        ref_period_end: Date = ...,
        day_counter: DayCounter = ...,
        is_in_arrears: bool = ...,
    ) -> None: ...
    def rate(self) -> float: ...
    def amount(self) -> float: ...
    def set_pricer(self, pricer: CmsSpreadCouponPricer) -> None: ...

class CPIInterpolationType:
    Flat: CPIInterpolationType
    Linear: CPIInterpolationType

class ZeroInflationTermStructureHandle:
    def empty(self) -> bool: ...
    def zero_rate(self, date: Date, extrapolate: bool = ...) -> float: ...
    def base_date(self) -> Date: ...
    def max_date(self) -> Date: ...
    def frequency(self) -> Frequency: ...
    def reference_date(self) -> Date: ...
    def has_seasonality(self) -> bool: ...
    def set_seasonality(self, seasonality: object | None = ...) -> None: ...

class RelinkableZeroInflationTermStructureHandle:
    def empty(self) -> bool: ...
    def link_to(self, handle: ZeroInflationTermStructureHandle) -> None: ...
    def as_handle(self) -> ZeroInflationTermStructureHandle: ...
    def zero_rate(self, date: Date, extrapolate: bool = ...) -> float: ...
    def has_seasonality(self) -> bool: ...
    def set_seasonality(self, seasonality: object | None = ...) -> None: ...

class ZeroInflationIndex:
    def name(self) -> str: ...
    def frequency(self) -> Frequency: ...
    def availability_lag(self) -> Period: ...
    def last_fixing_date(self) -> Date: ...
    def add_fixing(
        self, fixing_date: Date, fixing: float, force_overwrite: bool = ...
    ) -> None: ...
    def clear_fixings(self) -> None: ...
    def fixing(self, fixing_date: Date, forecast_today: bool = ...) -> float: ...

class ZeroInflationHelper: ...

class ZeroCouponInflationSwap:
    def __init__(
        self,
        type: SwapType,
        nominal: float,
        start_date: Date,
        maturity: Date,
        fix_calendar: Calendar,
        fix_convention: BusinessDayConvention,
        day_counter: DayCounter,
        fixed_rate: float,
        index: ZeroInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType,
        adjust_inf_obs_dates: bool = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def fair_rate(self) -> float: ...
    def fixed_rate(self) -> float: ...
    def nominal(self) -> float: ...
    def type(self) -> SwapType: ...
    def start_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def fixed_leg_NPV(self) -> float: ...
    def inflation_leg_NPV(self) -> float: ...
    def inflation_leg(self) -> list[object]: ...
    def fixed_leg(self) -> list[object]: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self, discount_curve: YieldTermStructureHandle
    ) -> None: ...

@overload
def UKRPI(handle: ZeroInflationTermStructureHandle = ...) -> ZeroInflationIndex: ...
@overload
def UKRPI(
    handle: RelinkableZeroInflationTermStructureHandle,
) -> ZeroInflationIndex: ...
def EUHICP(
    handle: ZeroInflationTermStructureHandle = ...,
) -> ZeroInflationIndex: ...
def InterpolatedZeroInflationCurve(
    reference_date: Date,
    dates: Sequence[Date],
    rates: Sequence[float],
    frequency: Frequency,
    day_counter: DayCounter,
) -> ZeroInflationTermStructureHandle: ...
def FlatZeroInflationCurve(
    reference_date: Date,
    base_date: Date,
    max_date: Date,
    rate: float,
    frequency: Frequency,
    day_counter: DayCounter,
) -> ZeroInflationTermStructureHandle: ...
def ZeroCouponInflationSwapHelper(
    quote: QuoteHandle,
    observation_lag: Period,
    maturity: Date,
    calendar: Calendar,
    payment_convention: BusinessDayConvention,
    day_counter: DayCounter,
    index: ZeroInflationIndex,
    observation_interpolation: CPIInterpolationType,
) -> ZeroInflationHelper: ...
def PiecewiseZeroInflationCurve(
    reference_date: Date,
    base_date: Date,
    frequency: Frequency,
    day_counter: DayCounter,
    helpers: Sequence[ZeroInflationHelper],
) -> ZeroInflationTermStructureHandle: ...

class YoYInflationTermStructureHandle:
    def empty(self) -> bool: ...
    def yoy_rate(self, date: Date, extrapolate: bool = ...) -> float: ...
    def base_date(self) -> Date: ...
    def base_rate(self) -> float: ...
    def max_date(self) -> Date: ...
    def frequency(self) -> Frequency: ...
    def reference_date(self) -> Date: ...
    def has_seasonality(self) -> bool: ...
    def set_seasonality(self, seasonality: object | None = ...) -> None: ...

class RelinkableYoYInflationTermStructureHandle:
    def empty(self) -> bool: ...
    def link_to(self, handle: YoYInflationTermStructureHandle) -> None: ...
    def as_handle(self) -> YoYInflationTermStructureHandle: ...
    def yoy_rate(self, date: Date, extrapolate: bool = ...) -> float: ...
    def has_seasonality(self) -> bool: ...
    def set_seasonality(self, seasonality: object | None = ...) -> None: ...

class YoYInflationIndex:
    def name(self) -> str: ...
    def frequency(self) -> Frequency: ...
    def availability_lag(self) -> Period: ...
    def last_fixing_date(self) -> Date: ...
    def ratio(self) -> bool: ...
    def add_fixing(
        self, fixing_date: Date, fixing: float, force_overwrite: bool = ...
    ) -> None: ...
    def clear_fixings(self) -> None: ...
    def fixing(self, fixing_date: Date, forecast_today: bool = ...) -> float: ...

class YoYInflationHelper: ...

class YearOnYearInflationSwap:
    def __init__(
        self,
        type: SwapType,
        nominal: float,
        fixed_schedule: Schedule,
        fixed_rate: float,
        fixed_day_count: DayCounter,
        yoy_schedule: Schedule,
        yoy_index: YoYInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType,
        spread: float,
        yoy_day_count: DayCounter,
        payment_calendar: Calendar,
        payment_convention: BusinessDayConvention = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def fair_rate(self) -> float: ...
    def fair_spread(self) -> float: ...
    def fixed_rate(self) -> float: ...
    def spread(self) -> float: ...
    def nominal(self) -> float: ...
    def type(self) -> SwapType: ...
    def start_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def fixed_leg_NPV(self) -> float: ...
    def yoy_leg_NPV(self) -> float: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self, discount_curve: YieldTermStructureHandle
    ) -> None: ...

@overload
def make_yoy_inflation_index(
    underlying: ZeroInflationIndex,
    handle: YoYInflationTermStructureHandle = ...,
) -> YoYInflationIndex: ...
@overload
def make_yoy_inflation_index(
    underlying: ZeroInflationIndex,
    handle: RelinkableYoYInflationTermStructureHandle,
) -> YoYInflationIndex: ...
@overload
def YYUKRPI(handle: YoYInflationTermStructureHandle = ...) -> YoYInflationIndex: ...
@overload
def YYUKRPI(
    handle: RelinkableYoYInflationTermStructureHandle,
) -> YoYInflationIndex: ...
def YYEUHICP(
    handle: YoYInflationTermStructureHandle = ...,
) -> YoYInflationIndex: ...
def InterpolatedYoYInflationCurve(
    reference_date: Date,
    dates: Sequence[Date],
    rates: Sequence[float],
    frequency: Frequency,
    day_counter: DayCounter,
) -> YoYInflationTermStructureHandle: ...
def FlatYoYInflationCurve(
    reference_date: Date,
    base_date: Date,
    max_date: Date,
    rate: float,
    frequency: Frequency,
    day_counter: DayCounter,
) -> YoYInflationTermStructureHandle: ...
def YearOnYearInflationSwapHelper(
    quote: QuoteHandle,
    observation_lag: Period,
    maturity: Date,
    calendar: Calendar,
    payment_convention: BusinessDayConvention,
    day_counter: DayCounter,
    index: YoYInflationIndex,
    observation_interpolation: CPIInterpolationType,
    nominal: YieldTermStructureHandle,
) -> YoYInflationHelper: ...
def PiecewiseYoYInflationCurve(
    reference_date: Date,
    base_date: Date,
    base_yoy_rate: float,
    frequency: Frequency,
    day_counter: DayCounter,
    helpers: Sequence[YoYInflationHelper],
) -> YoYInflationTermStructureHandle: ...

class YoYInflationCapFloorType:
    Cap: YoYInflationCapFloorType
    Floor: YoYInflationCapFloorType
    Collar: YoYInflationCapFloorType

class YoYOptionletVolatilitySurfaceHandle:
    def empty(self) -> bool: ...
    def volatility(
        self, date: Date, strike: float, extrapolate: bool = ...
    ) -> float: ...

class YoYInflationCapFloor:
    def __init__(
        self,
        type: YoYInflationCapFloorType,
        schedule: Schedule,
        index: YoYInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType,
        strike: float,
        payment_calendar: Calendar,
        day_counter: DayCounter,
        nominal: float = ...,
        payment_convention: BusinessDayConvention = ...,
        fixing_days: int = ...,
        floor_strike: float | None = ...,
    ) -> None: ...
    def __init__(
        self,
        type: YoYInflationCapFloorType,
        yoy_leg: Sequence[object],
        strike: float,
        floor_strike: float | None = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def type(self) -> YoYInflationCapFloorType: ...
    def start_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def is_expired(self) -> bool: ...
    def atm_rate(self, discount_curve: YieldTermStructureHandle) -> float: ...
    def set_pricing_engine(
        self,
        index: YoYInflationIndex,
        volatility: YoYOptionletVolatilitySurfaceHandle,
        nominal: YieldTermStructureHandle,
        model: str = ...,
    ) -> None: ...

def ConstantYoYOptionletVolatility(
    volatility: float,
    settlement_days: int,
    calendar: Calendar,
    bdc: BusinessDayConvention,
    day_counter: DayCounter,
    observation_lag: Period,
    frequency: Frequency,
    index_is_interpolated: bool = ...,
    min_strike: float = ...,
    max_strike: float = ...,
    vol_type: VolatilityType = ...,
    displacement: float = ...,
) -> YoYOptionletVolatilitySurfaceHandle: ...
def make_yoy_inflation_capfloor(
    type: YoYInflationCapFloorType,
    index: YoYInflationIndex,
    length_years: int,
    calendar: Calendar,
    observation_lag: Period,
    observation_interpolation: CPIInterpolationType,
    strike: float,
    nominal: float = ...,
    effective_date: Date = ...,
    day_counter: DayCounter = ...,
    payment_convention: BusinessDayConvention = ...,
) -> YoYInflationCapFloor: ...

def InterpolatedZeroCurve(
    dates: Sequence[Date],
    yields: Sequence[float],
    day_counter: DayCounter,
    interpolation: str = ...,
) -> YieldTermStructureHandle: ...
def GBPLibor(
    tenor: Period, handle: YieldTermStructureHandle = ...
) -> IborIndex: ...
def cpi_lagged_fixing(
    index: ZeroInflationIndex,
    date: Date,
    observation_lag: Period,
    interpolation: CPIInterpolationType,
) -> float: ...

class CPISwap:
    def __init__(
        self,
        type: SwapType,
        nominal: float,
        subtract_inflation_nominal: bool,
        spread: float,
        float_day_count: DayCounter,
        float_schedule: Schedule,
        float_roll: BusinessDayConvention,
        fixing_days: int,
        float_index: IborIndex | None,
        fixed_rate: float,
        base_cpi: float,
        fixed_day_count: DayCounter,
        fixed_schedule: Schedule,
        fixed_roll: BusinessDayConvention,
        observation_lag: Period,
        fixed_index: ZeroInflationIndex,
        observation_interpolation: CPIInterpolationType = ...,
        inflation_nominal: float = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def fair_rate(self) -> float: ...
    def fair_spread(self) -> float: ...
    def fixed_rate(self) -> float: ...
    def base_CPI(self) -> float: ...
    def spread(self) -> float: ...
    def nominal(self) -> float: ...
    def inflation_nominal(self) -> float: ...
    def type(self) -> SwapType: ...
    def fixed_leg_NPV(self) -> float: ...
    def float_leg_NPV(self) -> float: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self, discount_curve: YieldTermStructureHandle
    ) -> None: ...

class CPIBond:
    def __init__(
        self,
        settlement_days: int,
        face_amount: float,
        base_cpi: float,
        observation_lag: Period,
        cpi_index: ZeroInflationIndex,
        observation_interpolation: CPIInterpolationType,
        schedule: Schedule,
        coupons: Sequence[float],
        accrual_day_counter: DayCounter,
        payment_convention: BusinessDayConvention = ...,
        issue_date: Date = ...,
        payment_calendar: Calendar = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def base_CPI(self) -> float: ...
    def settlement_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self, discount_curve: YieldTermStructureHandle
    ) -> None: ...

class Matrix:
    def __init__(
        self, rows: int, columns: int, data: Sequence[float]
    ) -> None: ...
    def rows(self) -> int: ...
    def columns(self) -> int: ...
    def at(self, row: int, column: int) -> float: ...

class CPICapFloorTermPriceSurfaceHandle:
    def empty(self) -> bool: ...
    def price(self, tenor: Period, strike: float) -> float: ...
    def cap_price(self, tenor: Period, strike: float) -> float: ...
    def floor_price(self, tenor: Period, strike: float) -> float: ...
    def atm_rate(self, maturity: Date) -> float: ...

class CPICapFloor:
    def __init__(
        self,
        type: OptionType,
        nominal: float,
        start_date: Date,
        base_cpi: float,
        maturity: Date,
        fix_calendar: Calendar,
        fix_convention: BusinessDayConvention,
        pay_calendar: Calendar,
        pay_convention: BusinessDayConvention,
        strike: float,
        index: ZeroInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def type(self) -> OptionType: ...
    def nominal(self) -> float: ...
    def strike(self) -> float: ...
    def fixing_date(self) -> Date: ...
    def pay_date(self) -> Date: ...
    def is_expired(self) -> bool: ...
    def set_pricing_engine(
        self, price_surface: CPICapFloorTermPriceSurfaceHandle
    ) -> None: ...

def InterpolatedCPICapFloorTermPriceSurface(
    nominal: float,
    base_rate: float,
    observation_lag: Period,
    calendar: Calendar,
    bdc: BusinessDayConvention,
    day_counter: DayCounter,
    index: ZeroInflationIndex,
    observation_interpolation: CPIInterpolationType,
    nominal_curve: YieldTermStructureHandle,
    cap_strikes: Sequence[float],
    floor_strikes: Sequence[float],
    maturities: Sequence[Period],
    cap_prices: Matrix,
    floor_prices: Matrix,
) -> CPICapFloorTermPriceSurfaceHandle: ...

class Seasonality: ...

class MultiplicativePriceSeasonality(Seasonality):
    def __init__(
        self,
        seasonality_base_date: Date,
        frequency: Frequency,
        seasonality_factors: Sequence[float],
    ) -> None: ...
    def set(
        self,
        seasonality_base_date: Date,
        frequency: Frequency,
        seasonality_factors: Sequence[float],
    ) -> None: ...
    def seasonality_base_date(self) -> Date: ...
    def frequency(self) -> Frequency: ...
    def seasonality_factors(self) -> list[float]: ...
    def seasonality_factor(self, date: Date) -> float: ...

class KerkhofSeasonality(MultiplicativePriceSeasonality):
    def __init__(
        self,
        seasonality_base_date: Date,
        seasonality_factors: Sequence[float],
    ) -> None: ...

def inflation_period(
    date: Date, frequency: Frequency
) -> tuple[Date, Date]: ...

class CashFlow:
    def amount(self) -> float: ...
    def date(self) -> Date: ...
    def has_occurred(self, ref_date: Date = ...) -> bool: ...

class InflationCouponPricer: ...

class CPICouponPricer(InflationCouponPricer):
    def __init__(
        self, nominal: YieldTermStructureHandle = ...
    ) -> None: ...

class CPICoupon(CashFlow):
    def __init__(
        self,
        base_cpi: float,
        payment_date: Date,
        nominal: float,
        start_date: Date,
        end_date: Date,
        index: ZeroInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType,
        day_counter: DayCounter,
        fixed_rate: float,
    ) -> None: ...
    def rate(self) -> float: ...
    def fixed_rate(self) -> float: ...
    def base_CPI(self) -> float: ...
    def index_fixing(self) -> float: ...
    def adjusted_index_growth(self) -> float: ...
    def fixing_date(self) -> Date: ...
    def nominal(self) -> float: ...
    def set_pricer(self, pricer: InflationCouponPricer) -> None: ...

def make_cpi_leg(
    schedule: Schedule,
    index: ZeroInflationIndex,
    observation_lag: Period,
    day_counter: DayCounter,
    base_cpi: float | None = ...,
    base_date: Date = ...,
    notional: float = ...,
    fixed_rate: float = ...,
    payment_convention: BusinessDayConvention = ...,
    payment_calendar: Calendar = ...,
    observation_interpolation: CPIInterpolationType = ...,
    subtract_inflation_nominal: bool = ...,
) -> list[CashFlow]: ...
def set_cpi_coupon_pricer(
    leg: Sequence[CashFlow], pricer: InflationCouponPricer
) -> None: ...
def cashflows_npv(
    leg: Sequence[CashFlow],
    discount_curve: YieldTermStructureHandle,
    settlement: Date,
    include_settlement_date: bool = ...,
) -> float: ...
def cashflows_accrued_amount(
    leg: Sequence[CashFlow],
    settlement: Date,
    include_settlement_date: bool = ...,
) -> float: ...

class YoYInflationCouponPricer(InflationCouponPricer):
    def __init__(
        self,
        nominal: YieldTermStructureHandle = ...,
        caplet_vol: YoYOptionletVolatilitySurfaceHandle = ...,
    ) -> None: ...

class BlackYoYInflationCouponPricer(YoYInflationCouponPricer):
    def __init__(
        self,
        nominal: YieldTermStructureHandle = ...,
        caplet_vol: YoYOptionletVolatilitySurfaceHandle = ...,
    ) -> None: ...

class UnitDisplacedBlackYoYInflationCouponPricer(YoYInflationCouponPricer):
    def __init__(
        self,
        nominal: YieldTermStructureHandle = ...,
        caplet_vol: YoYOptionletVolatilitySurfaceHandle = ...,
    ) -> None: ...

class BachelierYoYInflationCouponPricer(YoYInflationCouponPricer):
    def __init__(
        self,
        nominal: YieldTermStructureHandle = ...,
        caplet_vol: YoYOptionletVolatilitySurfaceHandle = ...,
    ) -> None: ...

class YoYInflationCoupon(CashFlow):
    def __init__(
        self,
        payment_date: Date,
        nominal: float,
        start_date: Date,
        end_date: Date,
        fixing_days: int,
        index: YoYInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType,
        day_counter: DayCounter,
        gearing: float = ...,
        spread: float = ...,
    ) -> None: ...
    def rate(self) -> float: ...
    def gearing(self) -> float: ...
    def spread(self) -> float: ...
    def index_fixing(self) -> float: ...
    def adjusted_fixing(self) -> float: ...
    def fixing_date(self) -> Date: ...
    def nominal(self) -> float: ...
    def interpolation(self) -> CPIInterpolationType: ...
    def yoy_index(self) -> YoYInflationIndex: ...
    def set_pricer(self, pricer: InflationCouponPricer) -> None: ...

def make_yoy_inflation_leg(
    schedule: Schedule,
    payment_calendar: Calendar,
    index: YoYInflationIndex,
    observation_lag: Period,
    observation_interpolation: CPIInterpolationType,
    day_counter: DayCounter,
    notional: float = ...,
    fixing_days: int = ...,
    gearing: float = ...,
    spread: float = ...,
    payment_convention: BusinessDayConvention = ...,
    cap: float | None = ...,
    floor: float | None = ...,
) -> list[CashFlow]: ...
def set_yoy_coupon_pricer(
    leg: Sequence[CashFlow], pricer: InflationCouponPricer
) -> None: ...

class CappedFlooredYoYInflationCoupon(YoYInflationCoupon):
    def __init__(
        self,
        underlying: YoYInflationCoupon,
        cap: float | None = ...,
        floor: float | None = ...,
    ) -> None: ...
    def __init__(
        self,
        payment_date: Date,
        nominal: float,
        start_date: Date,
        end_date: Date,
        fixing_days: int,
        index: YoYInflationIndex,
        observation_lag: Period,
        observation_interpolation: CPIInterpolationType,
        day_counter: DayCounter,
        gearing: float = ...,
        spread: float = ...,
        cap: float | None = ...,
        floor: float | None = ...,
    ) -> None: ...
    def rate(self) -> float: ...
    def cap(self) -> float: ...
    def floor(self) -> float: ...
    def effective_cap(self) -> float: ...
    def effective_floor(self) -> float: ...
    def underlying_rate(self) -> float: ...
    def is_capped(self) -> bool: ...
    def is_floored(self) -> bool: ...
    def set_pricer(self, pricer: YoYInflationCouponPricer) -> None: ...

class IndexedCashFlow(CashFlow):
    def notional(self) -> float: ...
    def base_date(self) -> Date: ...
    def fixing_date(self) -> Date: ...
    def growth_only(self) -> bool: ...
    def base_fixing(self) -> float: ...
    def index_fixing(self) -> float: ...

class CPICashFlow(IndexedCashFlow):
    def __init__(
        self,
        notional: float,
        index: ZeroInflationIndex,
        base_date: Date,
        base_fixing: float,
        observation_date: Date,
        observation_lag: Period,
        interpolation: CPIInterpolationType,
        payment_date: Date,
        growth_only: bool = ...,
    ) -> None: ...
    def observation_date(self) -> Date: ...
    def observation_lag(self) -> Period: ...
    def interpolation(self) -> CPIInterpolationType: ...
    def frequency(self) -> Frequency: ...
    def cpi_index(self) -> ZeroInflationIndex: ...

class ZeroInflationCashFlow(IndexedCashFlow):
    def __init__(
        self,
        notional: float,
        index: ZeroInflationIndex,
        observation_interpolation: CPIInterpolationType,
        start_date: Date,
        end_date: Date,
        observation_lag: Period,
        payment_date: Date,
        growth_only: bool = ...,
    ) -> None: ...
    def zero_inflation_index(self) -> ZeroInflationIndex: ...
    def observation_interpolation(self) -> CPIInterpolationType: ...

class YoYCapFloorTermPriceSurfaceHandle:
    def empty(self) -> bool: ...
    def price(self, tenor: Period, strike: float) -> float: ...
    def cap_price(self, tenor: Period, strike: float) -> float: ...
    def floor_price(self, tenor: Period, strike: float) -> float: ...
    def atm_yoy_swap_rate(
        self, date: Date, extrapolate: bool = ...
    ) -> float: ...
    def atm_yoy_rate(self, date: Date, extrapolate: bool = ...) -> float: ...
    def atm_yoy_swap_time_rates(self) -> tuple[list[float], list[float]]: ...
    def atm_yoy_swap_date_rates(self) -> tuple[list[Date], list[float]]: ...
    def yoy_ts(self) -> YoYInflationTermStructureHandle: ...
    def cap_strikes(self) -> list[float]: ...
    def floor_strikes(self) -> list[float]: ...
    def maturities(self) -> list[Period]: ...
    def observation_lag(self) -> Period: ...

def InterpolatedYoYCapFloorTermPriceSurface(
    fixing_days: int,
    yy_lag: Period,
    yoy_index: YoYInflationIndex,
    observation_interpolation: CPIInterpolationType,
    nominal_curve: YieldTermStructureHandle,
    day_counter: DayCounter,
    calendar: Calendar,
    bdc: BusinessDayConvention,
    cap_strikes: Sequence[float],
    floor_strikes: Sequence[float],
    maturities: Sequence[Period],
    cap_prices: Matrix,
    floor_prices: Matrix,
) -> YoYCapFloorTermPriceSurfaceHandle: ...

class BondPriceType:
    Clean: BondPriceType
    Dirty: BondPriceType

class BondPrice:
    def __init__(
        self, amount: float, type: BondPriceType = ...
    ) -> None: ...
    def amount(self) -> float: ...
    def type(self) -> BondPriceType: ...
    def is_valid(self) -> bool: ...

class CallabilityType:
    Call: CallabilityType
    Put: CallabilityType

class Callability:
    def price(self) -> BondPrice: ...
    def type(self) -> CallabilityType: ...
    def date(self) -> Date: ...

@overload
def make_callability(
    price: BondPrice, type: CallabilityType, date: Date
) -> Callability: ...
@overload
def make_callability(
    amount: float,
    price_type: BondPriceType,
    type: CallabilityType,
    date: Date,
) -> Callability: ...

class CallableFixedRateBond:
    def __init__(
        self,
        settlement_days: int,
        face_amount: float,
        schedule: Schedule,
        coupons: Sequence[float],
        accrual_day_counter: DayCounter,
        payment_convention: BusinessDayConvention = ...,
        redemption: float = ...,
        issue_date: Date = ...,
        put_call_schedule: Sequence[Callability] = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def settlement_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def set_tree_pricing_engine(
        self,
        model: HullWhite,
        time_steps: int = ...,
        discount_curve: YieldTermStructureHandle = ...,
    ) -> None: ...

class CallableZeroCouponBond:
    def __init__(
        self,
        settlement_days: int,
        face_amount: float,
        calendar: Calendar,
        maturity_date: Date,
        day_counter: DayCounter,
        payment_convention: BusinessDayConvention = ...,
        redemption: float = ...,
        issue_date: Date = ...,
        put_call_schedule: Sequence[Callability] = ...,
    ) -> None: ...
    def NPV(self) -> float: ...
    def clean_price(self) -> float: ...
    def dirty_price(self) -> float: ...
    def settlement_date(self) -> Date: ...
    def maturity_date(self) -> Date: ...
    def set_tree_pricing_engine(
        self,
        model: HullWhite,
        time_steps: int = ...,
        discount_curve: YieldTermStructureHandle = ...,
    ) -> None: ...

# --- Phase 24: currencies / money / FX forward ---

class Currency:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def code(self) -> str: ...
    def numeric_code(self) -> int: ...
    def symbol(self) -> str: ...
    def fraction_symbol(self) -> str: ...
    def fractions_per_unit(self) -> int: ...
    def empty(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __mul__(self, value: float) -> Money: ...
    def __rmul__(self, value: float) -> Money: ...

def USDCurrency() -> Currency: ...
def EURCurrency() -> Currency: ...
def GBPCurrency() -> Currency: ...
def SGDCurrency() -> Currency: ...

class MoneyConversionType:
    NoConversion: MoneyConversionType
    BaseCurrencyConversion: MoneyConversionType
    AutomatedConversion: MoneyConversionType

def set_money_conversion(conversion_type: MoneyConversionType) -> None: ...
def get_money_conversion() -> MoneyConversionType: ...

class Money:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, currency: Currency, value: float) -> None: ...
    @overload
    def __init__(self, value: float, currency: Currency) -> None: ...
    def currency(self) -> Currency: ...
    def value(self) -> float: ...
    def rounded(self) -> Money: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __mul__(self, x: float) -> Money: ...
    def __rmul__(self, x: float) -> Money: ...
    def __truediv__(self, x: float) -> Money: ...

class ExchangeRateType:
    Direct: ExchangeRateType
    Derived: ExchangeRateType

class ExchangeRate:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, source: Currency, target: Currency, rate: float
    ) -> None: ...
    def source(self) -> Currency: ...
    def target(self) -> Currency: ...
    def type(self) -> ExchangeRateType: ...
    def rate(self) -> float: ...
    def exchange(self, amount: Money) -> Money: ...
    @staticmethod
    def chain(r1: ExchangeRate, r2: ExchangeRate) -> ExchangeRate: ...

def exchange_rate_manager_clear() -> None: ...
def exchange_rate_manager_add(
    rate: ExchangeRate,
    start_date: Date = ...,
    end_date: Date = ...,
) -> None: ...
def exchange_rate_manager_lookup(
    source: Currency,
    target: Currency,
    date: Date = ...,
    type: ExchangeRateType = ...,
) -> ExchangeRate: ...

class FxForward:
    @overload
    def __init__(
        self,
        source_nominal: float,
        source_currency: Currency,
        target_nominal: float,
        target_currency: Currency,
        maturity_date: Date,
        pay_source_currency: bool,
        settlement_days: int = ...,
        payment_calendar: Calendar = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        source_nominal: float,
        source_currency: Currency,
        target_currency: Currency,
        forward_rate: float,
        maturity_date: Date,
        pay_source_currency: bool,
        settlement_days: int = ...,
        payment_calendar: Calendar = ...,
    ) -> None: ...
    def source_nominal(self) -> float: ...
    def target_nominal(self) -> float: ...
    def source_currency(self) -> Currency: ...
    def target_currency(self) -> Currency: ...
    def maturity_date(self) -> Date: ...
    def pay_source_currency(self) -> bool: ...
    def forward_rate(self) -> float: ...
    def settlement_days(self) -> int: ...
    def settlement_calendar(self) -> Calendar: ...
    def settlement_date(self) -> Date: ...
    def is_expired(self) -> bool: ...
    def NPV(self) -> float: ...
    def fair_forward_rate(self) -> float: ...
    def npv_source_currency(self) -> float: ...
    def npv_target_currency(self) -> float: ...
    @overload
    def set_pricing_engine(
        self,
        source_curve: YieldTermStructureHandle,
        target_curve: YieldTermStructureHandle,
        spot_fx: QuoteHandle,
    ) -> None: ...
    @overload
    def set_pricing_engine(
        self,
        source_curve: YieldTermStructureHandle,
        target_curve: YieldTermStructureHandle,
        spot_fx: float,
    ) -> None: ...

__version__: str
