/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */


#include <ql/legacy/libormarketmodels/all.hpp>
#include <ql/legacy/pricers/all.hpp>
