/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/models/shortrate/twofactormodels/g2.hpp>
#include <ql/models/shortrate/twofactormodels/gaussian2dmodel.hpp>
#include <ql/models/shortrate/twofactormodels/gsr2.hpp>

