"""Report QuantLib tests whose recorded execution times exceed the limit."""

import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from typing import Callable, DefaultDict, Iterator, List, NamedTuple, Optional, Tuple

regex1 = re.compile(r".*test_case\(&(.*?)__(.*?)\)")
regex2 = re.compile(r".*ext__bind\(&(.*?)__(.*?)__.*\)\)")
regex3 = re.compile(r".*{_?([a-zA-Z]*Test)__([a-zA-Z]*?)\(")
regex4 = re.compile(r"([^.]+)\.(.+)")


TestName = Tuple[str, str]


class Case(NamedTuple):
    """Recorded execution times for one test case."""

    times: List[float]


def parse_simple(t: ET.Element) -> Optional[TestName]:
    """Extract names from a directly registered test case."""
    # test names get mangled - here we extract class and method name
    m = regex1.match(t.attrib["name"])
    if m:
        return m.group(1), m.group(2)
    return None


def parse_bound(t: ET.Element) -> Optional[TestName]:
    """Extract names from a test case registered through a bind expression."""
    # same, for cases inside a bind
    m = regex2.match(t.attrib["name"])
    if m:
        return m.group(1), m.group(2)
    return None


def parse_lambda(t: ET.Element) -> Optional[TestName]:
    """Extract names from a test case registered through a lambda."""
    # same, for cases inside a lambda
    m = regex3.match(t.attrib["name"])
    if m:
        return m.group(1), m.group(2)
    return None


def parse_simple_auto_generated(t: ET.Element) -> Optional[TestName]:
    """Extract names generated by Boost.Test automatic registration."""
    # used for classname generated by automated registration using boost test
    m = regex4.match(t.attrib["classname"])
    if m:
        return m.groups()[1], t.attrib["name"]
    return None


def extract_test_info(filename: str) -> Iterator[Tuple[str, str, float]]:
    """Yield test class, method, and duration records from a JUnit XML file."""
    # all.xml is generated locally by the test runner, not supplied by an untrusted user.
    root = ET.parse(filename).getroot()  # nosec B314
    tests = root.findall("testcase")
    for t in tests:
        if t.findall("skipped"):
            continue
        test_name = (
            parse_simple(t)
            or parse_bound(t)
            or parse_lambda(t)
            or parse_simple_auto_generated(t)
        )
        if test_name is None:
            raise ValueError(f"Could not parse test name from {t.attrib}")
        cls, method = test_name
        time = float(t.attrib["time"])
        yield (cls, method, time)


def collect() -> DefaultDict[TestName, Case]:
    """Collect recorded durations by test class and method."""
    timings: DefaultDict[TestName, Case] = defaultdict(lambda: Case([]))
    for cls, method, time in extract_test_info("all.xml"):
        c = timings[(cls, method)]
        c.times.append(time)
    return timings


def check(
    timings: DefaultDict[TestName, Case],
    condition: Callable[[Case], bool],
    action: str,
) -> bool:
    """Report matching tests and return whether any were found."""
    has_errors = False
    for cls, method in timings:
        c = timings[(cls, method)]
        if condition(c):
            print(
                f"{cls}.{method} ({min(c.times):.2f} s / {max(c.times):.2f} s) {action}"
            )
            has_errors = True
    return has_errors


def main() -> int:
    """Check collected timings and return a process exit status."""
    timings = collect()
    errors = check(
        timings,
        lambda c: max(c.times) > 20.0,
        "should be kept reliably under 20 seconds",
    )
    return int(errors)


if __name__ == "__main__":
    sys.exit(main())
