/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/termstructures/volatilities/equity/blackconstantvol.hpp>
#include <ql/termstructures/volatilities/equity/blackvariancecurve.hpp>
#include <ql/termstructures/volatilities/equity/blackvariancesurface.hpp>
#include <ql/termstructures/volatilities/equity/impliedvoltermstructure.hpp>
#include <ql/termstructures/volatilities/equity/localconstantvol.hpp>
#include <ql/termstructures/volatilities/equity/localvolcurve.hpp>
#include <ql/termstructures/volatilities/equity/localvolsurface.hpp>

