/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/marketmodels/products/compositeproduct.hpp>
#include <ql/marketmodels/products/multiproductcomposite.hpp>
#include <ql/marketmodels/products/multiproductmultistep.hpp>
#include <ql/marketmodels/products/multiproductonestep.hpp>
#include <ql/marketmodels/products/singleproductcomposite.hpp>

#include <ql/marketmodels/products/onestep/all.hpp>
#include <ql/marketmodels/products/multistep/all.hpp>
