name: Fix deprecated uses of ext namespace
on:
  push:
    branches-ignore:
      - 'dependabot/**'
jobs:
  check-namespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Check
      run: |
        shopt -s globstar
        sed -i -e 's/ext::any\b/std::any/g' **/*.[hc]pp
        sed -i -e 's/ext::any_cast\b/std::any_cast/g' **/*.[hc]pp
        sed -i -e 's/ext::optional\b/std::optional/g' **/*.[hc]pp
        sed -i -e 's/ext::nullopt\b/std::nullopt/g' **/*.[hc]pp
    - uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
        push-to-fork: ${{ vars.MACHINE_ACCOUNT }}/QuantLib
        branch: fix-ext-namespace-${{ github.ref_name }}
        delete-branch: true
        commit-message: 'Fix deprecated uses of ext namespace'
        title: 'Fix deprecated uses of ext namespace'
        author: lballabio[bot] <224797326+lballabio-bot@users.noreply.github.com>
