name: Pre-release checks
on:
  workflow_dispatch:

jobs:
  full-linux-tests:
    uses: ./.github/workflows/linux-full-tests.yml
  full-msvc-tests:
    uses: ./.github/workflows/msvc-all-configs.yml
  linux-alt-config:
    uses: ./.github/workflows/linux-nondefault.yml
  msvc-alt-config:
    uses: ./.github/workflows/msvc-nondefault.yml
  macos-alt-config:
    uses: ./.github/workflows/macos-nondefault.yml
  cmake-latest:
    uses: ./.github/workflows/cmake-latest-runners.yml

