name: Replace Boost macros that might not work with AAD types
on:
  push:
    branches-ignore:
      - 'dependabot/**'
jobs:
  check-namespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Check
      run: |
        sed -i -e 's/BOOST_CHECK_SMALL\b/QL_CHECK_SMALL/g' test-suite/*.cpp
        sed -i -e 's/BOOST_CHECK_CLOSE\b/QL_CHECK_CLOSE/g' test-suite/*.cpp
        sed -i -e 's/BOOST_CHECK_CLOSE_FRACTION\b/QL_CHECK_CLOSE_FRACTION/g' test-suite/*.cpp
    - uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
        push-to-fork: ${{ vars.MACHINE_ACCOUNT }}/QuantLib
        branch: fix-boost-test-macros-${{ github.ref_name }}
        delete-branch: true
        commit-message: 'Replace Boost macros that might not work with AAD types'
        title: 'Replace Boost macros that might not work with AAD types'
        author: lballabio[bot] <224797326+lballabio-bot@users.noreply.github.com>
