name: Replace Boost macros that might not work with AAD types

on:
  push:
    branches-ignore:
      - 'dependabot/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-namespaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Boost macros
        shell: bash
        run: |
          sed -i -e 's/BOOST_CHECK_SMALL\b/QL_CHECK_SMALL/g' test-suite/*.cpp
          sed -i -e 's/BOOST_CHECK_CLOSE\b/QL_CHECK_CLOSE/g' test-suite/*.cpp
          sed -i -e 's/BOOST_CHECK_CLOSE_FRACTION\b/QL_CHECK_CLOSE_FRACTION/g' test-suite/*.cpp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: fix-boost-test-macros-${{ github.ref_name }}
          delete-branch: true
          commit-message: "Replace Boost macros that might not work with AAD types"
          title: "Replace Boost macros that might not work with AAD types"
          body: "Automated replacement of Boost test macros with QL equivalents."