name: Apply clang-tidy fixes
on:
  push:
    branches:
      - '**'
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy-10 libboost-dev
    - name: Check
      run: |
        find ql -name *.[hc]pp -not -name config.*.hpp -not -name all.hpp -not -name quantlib.hpp >> filelist
        find test-suite -name *.cpp >> filelist
        find Examples -name *.cpp >> filelist
        cat filelist | sort | xargs -n 1 ./tools/run_tidy.sh
        rm filelist
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: clang-tidy-fixes-${{ github.ref }}
        delete-branch: true
        commit-message: 'Automated fixes by clang-tidy'
        title: 'Automated fixes by clang-tidy'
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        body: |
          This is an automated PR generated by the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.

          Please review the changes before merging.

