name: Test clang-tidy installation
on:
  - push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get install -y clang-tidy libboost-dev
    - name: Check
      run: |
        find . -name *.[hc]pp | grep -v 'config\.msvc\.hpp$' | sort | xargs -n 1 ./tools/run_tidy.sh 

